import{base64ToBytes,getCurrentHead,getFile,listDirectory,multiCommit,readFileBase64,readJsonFile,restorePathsFromCommit,textToBase64}from'./cms-github.js';

const SETTINGS='data/site-settings.json',SEO='data/site-seo.json',BACKUPS='data/site-auto-backups.json',PRESETS='data/theme-presets.json',SCHEDULE='data/site-schedule.json',LOGS='data/site-manager-log.json';
const MANAGED=['assets/pfp.jpg',SETTINGS,'assets/site-favicon.jpg','assets/site-background.jpg','assets/site-banner.jpg',SEO];
const IMAGE_PATHS=new Set(['assets/pfp.jpg','assets/site-favicon.jpg','assets/site-background.jpg','assets/site-banner.jpg']);
const LIBRARY_KINDS=['profile','favicon','background','banner'];
const defaults={bio:'He/Him — I build websites and Discord bots, and I make FNF mods for fun',statusText:'Available for Freelance',commissionOpen:true,commissionTotal:4,commissionUsed:0,backgroundEnabled:false,bannerEnabled:false,faviconEnabled:false,themeMode:'auto',mainColor:'#ffffff',secondaryColor:'#9f9f9f',accentColor:'#d7d7d7',maintenanceEnabled:false,maintenanceTitle:'Back soon',maintenanceMessage:'The site is being updated right now.',updatedAt:null};
const seoDefaults={title:'Immortal | Developer, Discord Bots & FNF Mods',description:'Immortal is a developer portfolio featuring web projects, Discord bots, FNF modding, and current work.',themeColor:'#0a0a0a',image:'https://xm5o.github.io/assets/Immortal-site-banner.png',updatedAt:null};
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
function clamp(v,min,max,fallback){const n=parseInt(v,10);return Number.isFinite(n)?Math.max(min,Math.min(max,n)):fallback}
function text(v,max,fallback=''){const s=String(v??'').replace(/\s+/g,' ').trim();return(s||fallback).slice(0,max)}
function color(v,fallback){const s=String(v||'');return/^#[0-9a-f]{6}$/i.test(s)?s.toLowerCase():fallback}
function normalizeSettings(input={},current=defaults){const total=clamp(input.commissionTotal,1,12,clamp(current.commissionTotal,1,12,4)),used=clamp(input.commissionUsed,0,total,clamp(current.commissionUsed,0,total,0));return{bio:text(input.bio,220,current.bio||defaults.bio),statusText:text(input.statusText,72,current.statusText||defaults.statusText),commissionOpen:typeof input.commissionOpen==='boolean'?input.commissionOpen:Boolean(current.commissionOpen),commissionTotal:total,commissionUsed:used,backgroundEnabled:typeof input.backgroundEnabled==='boolean'?input.backgroundEnabled:Boolean(current.backgroundEnabled),bannerEnabled:typeof input.bannerEnabled==='boolean'?input.bannerEnabled:Boolean(current.bannerEnabled),faviconEnabled:typeof input.faviconEnabled==='boolean'?input.faviconEnabled:Boolean(current.faviconEnabled),themeMode:input.themeMode==='manual'?'manual':'auto',mainColor:color(input.mainColor,current.mainColor||defaults.mainColor),secondaryColor:color(input.secondaryColor,current.secondaryColor||defaults.secondaryColor),accentColor:color(input.accentColor,current.accentColor||defaults.accentColor),maintenanceEnabled:typeof input.maintenanceEnabled==='boolean'?input.maintenanceEnabled:Boolean(current.maintenanceEnabled),maintenanceTitle:text(input.maintenanceTitle,80,current.maintenanceTitle||defaults.maintenanceTitle),maintenanceMessage:text(input.maintenanceMessage,240,current.maintenanceMessage||defaults.maintenanceMessage),updatedAt:new Date().toISOString()}}
function normalizeSeo(input={},current=seoDefaults){let image=String(input.image??current.image??seoDefaults.image).trim();try{const u=new URL(image);if(u.protocol!=='https:')image=seoDefaults.image}catch{image=seoDefaults.image}return{title:text(input.title,90,current.title||seoDefaults.title),description:text(input.description,180,current.description||seoDefaults.description),themeColor:color(input.themeColor,current.themeColor||seoDefaults.themeColor),image,updatedAt:new Date().toISOString()}}
async function body(request,max=16*1024*1024){const raw=await request.text();if(raw.length>max)throw Object.assign(new Error('Request is too large.'),{status:413});try{return raw?JSON.parse(raw):{}}catch{throw Object.assign(new Error('Invalid JSON request.'),{status:400})}}
function jpeg64(value){try{const b=base64ToBytes(value);return b.length>2&&b[0]===255&&b[1]===216&&b[2]===255}catch{return false}}
async function currentSettings(env){return normalizeSettings(await readJsonFile(env,SETTINGS,env.GITHUB_BRANCH,defaults),defaults)}
async function currentSeo(env){return normalizeSeo(await readJsonFile(env,SEO,env.GITHUB_BRANCH,seoDefaults),seoDefaults)}
async function loadList(env,path){const value=await readJsonFile(env,path,env.GITHUB_BRANCH,[]);return Array.isArray(value)?value:[]}
function logEntry(action,detail=''){return{id:crypto.randomUUID(),action,detail:text(detail,160),at:new Date().toISOString()}}
async function listWithNew(env,path,entry,max=40){const list=await loadList(env,path);return[entry,...list].slice(0,max)}
function fileChange(path,value,encoding='utf-8'){return{path,content:value,encoding}}

async function publishAll(env,payload){const changes=[],summary=[];const parent=await getCurrentHead(env);const backups=await loadList(env,BACKUPS);const backup={id:crypto.randomUUID(),createdAt:new Date().toISOString(),baseCommit:parent,label:text(payload.label,70,'Automatic pre-publish backup'),undoneAt:null};
if(payload.settings){const settings=normalizeSettings(payload.settings,await currentSettings(env));changes.push(fileChange(SETTINGS,`${JSON.stringify(settings,null,2)}\n`));summary.push('settings')}
if(payload.seo){const seo=normalizeSeo(payload.seo,await currentSeo(env));changes.push(fileChange(SEO,`${JSON.stringify(seo,null,2)}\n`));summary.push('SEO')}
const files=Array.isArray(payload.files)?payload.files:[];for(const item of files){const path=String(item?.path||'');if(!IMAGE_PATHS.has(path)||!jpeg64(item?.base64))throw Object.assign(new Error(`Invalid managed image: ${path||'unknown'}`),{status:400});changes.push(fileChange(path,item.base64,'base64'));summary.push(path.split('/').pop());if(payload.saveToLibrary){const kind=path==='assets/pfp.jpg'?'profile':path.includes('favicon')?'favicon':path.includes('background')?'background':'banner';changes.push(fileChange(`assets/library/${kind}/${Date.now()}-${crypto.randomUUID().slice(0,8)}.jpg`,item.base64,'base64'))}}
if(!changes.length)throw Object.assign(new Error('There are no draft changes to publish.'),{status:400});changes.push(fileChange(BACKUPS,`${JSON.stringify([backup,...backups].slice(0,20),null,2)}\n`));const logs=await listWithNew(env,LOGS,logEntry('publish',summary.join(', ')));changes.push(fileChange(LOGS,`${JSON.stringify(logs,null,2)}\n`));const result=await multiCommit(env,changes,text(payload.message,100,'Publish site manager draft'),{parentSha:parent});return{...result,backupId:backup.id,summary}}

async function undoLast(env){const backups=await loadList(env,BACKUPS);const index=backups.findIndex(item=>item?.baseCommit&&!item.undoneAt);if(index<0)throw Object.assign(new Error('There is no automatic backup to undo to.'),{status:404});const backup=backups[index];backup.undoneAt=new Date().toISOString();const logs=await listWithNew(env,LOGS,logEntry('undo',`Restore ${String(backup.baseCommit).slice(0,7)}`));const extra=[fileChange(BACKUPS,`${JSON.stringify(backups,null,2)}\n`),fileChange(LOGS,`${JSON.stringify(logs,null,2)}\n`)];const result=await restorePathsFromCommit(env,backup.baseCommit,MANAGED,extra,`Undo last site manager publish`);return{...result,backup}}

async function health(env){let githubOk=false,latestCommit=null,liveOk=false,liveUpdatedAt=null,repoUpdatedAt=null;try{latestCommit=await getCurrentHead(env);githubOk=true}catch{}try{const s=await currentSettings(env);repoUpdatedAt=s.updatedAt||null}catch{}try{const r=await fetch(`https://xm5o.github.io/data/site-settings.json?health=${Date.now()}`,{cache:'no-store'});if(r.ok){const live=await r.json();liveUpdatedAt=live.updatedAt||null;liveOk=!repoUpdatedAt||liveUpdatedAt===repoUpdatedAt}}catch{}return{ok:true,workerOk:true,githubOk,liveOk,latestCommit,repoUpdatedAt,liveUpdatedAt,time:new Date().toISOString()}}

async function library(env){const items=[];for(const kind of LIBRARY_KINDS){for(const item of await listDirectory(env,`assets/library/${kind}`)){if(item.type==='file'&&/\.jpe?g$/i.test(item.name))items.push({kind,name:item.name,path:item.path,sha:item.sha,url:item.download_url})}}return items.sort((a,b)=>b.name.localeCompare(a.name)).slice(0,60)}
async function addLibrary(env,payload){const kind=LIBRARY_KINDS.includes(payload.kind)?payload.kind:null;if(!kind||!jpeg64(payload.base64))throw Object.assign(new Error('Invalid library image.'),{status:400});const name=`${Date.now()}-${text(payload.label,30,'image').replace(/[^a-z0-9_-]+/gi,'-')}.jpg`;return multiCommit(env,[fileChange(`assets/library/${kind}/${name}`,payload.base64,'base64')],`Add ${kind} image to library`)}

async function presets(env){return loadList(env,PRESETS)}
async function savePreset(env,payload){const list=await presets(env),head=await getCurrentHead(env);const item={id:crypto.randomUUID(),name:text(payload.name,60,'Theme preset'),createdAt:new Date().toISOString(),refCommit:head};const logs=await listWithNew(env,LOGS,logEntry('preset',`Saved ${item.name}`));const result=await multiCommit(env,[fileChange(PRESETS,`${JSON.stringify([item,...list].slice(0,30),null,2)}\n`),fileChange(LOGS,`${JSON.stringify(logs,null,2)}\n`)],`Save theme preset: ${item.name}`);return{item,result}}
async function applyPreset(env,id,message='Apply theme preset'){const list=await presets(env),item=list.find(v=>v.id===id);if(!item)throw Object.assign(new Error('Theme preset not found.'),{status:404});const parent=await getCurrentHead(env),backups=await loadList(env,BACKUPS),backup={id:crypto.randomUUID(),createdAt:new Date().toISOString(),baseCommit:parent,label:`Before preset: ${item.name}`,undoneAt:null};const logs=await listWithNew(env,LOGS,logEntry('preset-apply',item.name));const extra=[fileChange(BACKUPS,`${JSON.stringify([backup,...backups].slice(0,20),null,2)}\n`),fileChange(LOGS,`${JSON.stringify(logs,null,2)}\n`)];const result=await restorePathsFromCommit(env,item.refCommit,MANAGED,extra,message);return{item,result}}
async function deletePreset(env,id){const list=(await presets(env)).filter(v=>v.id!==id);return multiCommit(env,[fileChange(PRESETS,`${JSON.stringify(list,null,2)}\n`)],'Delete theme preset')}

async function schedules(env){return loadList(env,SCHEDULE)}
async function addSchedule(env,payload){const presetList=await presets(env),preset=presetList.find(v=>v.id===payload.presetId);if(!preset)throw Object.assign(new Error('Choose a valid preset.'),{status:400});const runAt=new Date(payload.runAt);if(!Number.isFinite(runAt.getTime())||runAt.getTime()<=Date.now())throw Object.assign(new Error('Scheduled time must be in the future.'),{status:400});const jobs=await schedules(env),job={id:crypto.randomUUID(),presetId:preset.id,presetName:preset.name,runAt:runAt.toISOString(),status:'pending',createdAt:new Date().toISOString()};await multiCommit(env,[fileChange(SCHEDULE,`${JSON.stringify([job,...jobs].slice(0,40),null,2)}\n`)],`Schedule preset: ${preset.name}`);return job}
async function deleteSchedule(env,id){const jobs=(await schedules(env)).filter(v=>v.id!==id);return multiCommit(env,[fileChange(SCHEDULE,`${JSON.stringify(jobs,null,2)}\n`)],'Delete scheduled site change')}

async function exportBackup(env){const files={};for(const path of MANAGED){const content=await readFileBase64(env,path,env.GITHUB_BRANCH);if(content)files[path]=content}return{version:1,exportedAt:new Date().toISOString(),repository:env.GITHUB_REPO,files,presets:await presets(env)}}
async function importBackup(env,payload){if(Number(payload.version)!==1||!payload.files||typeof payload.files!=='object')throw Object.assign(new Error('Unsupported backup file.'),{status:400});const parent=await getCurrentHead(env),backups=await loadList(env,BACKUPS),backup={id:crypto.randomUUID(),createdAt:new Date().toISOString(),baseCommit:parent,label:'Before backup import',undoneAt:null},changes=[];for(const path of MANAGED){if(payload.files[path])changes.push(fileChange(path,String(payload.files[path]),'base64'))}if(!changes.length)throw Object.assign(new Error('Backup contains no managed files.'),{status:400});if(Array.isArray(payload.presets))changes.push(fileChange(PRESETS,`${JSON.stringify(payload.presets.slice(0,30),null,2)}\n`));changes.push(fileChange(BACKUPS,`${JSON.stringify([backup,...backups].slice(0,20),null,2)}\n`));changes.push(fileChange(LOGS,`${JSON.stringify(await listWithNew(env,LOGS,logEntry('import','Imported admin backup')),null,2)}\n`));return multiCommit(env,changes,'Import site manager backup',{parentSha:parent})}

export async function processSchedule(env){const jobs=await schedules(env),due=jobs.filter(j=>j.status==='pending'&&new Date(j.runAt).getTime()<=Date.now()).sort((a,b)=>new Date(a.runAt)-new Date(b.runAt));for(const job of due.slice(0,3)){try{await applyPreset(env,job.presetId,`Scheduled preset: ${job.presetName}`);job.status='completed';job.completedAt=new Date().toISOString()}catch(error){job.status='failed';job.error=text(error.message,120);job.completedAt=new Date().toISOString()}await multiCommit(env,[fileChange(SCHEDULE,`${JSON.stringify(jobs,null,2)}\n`)],`Update scheduled change: ${job.presetName}`)}return due.length}

export async function handleCms(request,env){const url=new URL(request.url),path=url.pathname;try{
if(path==='/settings'&&request.method==='GET')return json({ok:true,settings:await currentSettings(env)});
if(path==='/settings'&&request.method==='POST'){const input=await body(request,65536),settings=normalizeSettings(input,await currentSettings(env));const r=await multiCommit(env,[fileChange(SETTINGS,`${JSON.stringify(settings,null,2)}\n`)],'Update managed site settings');return json({ok:true,settings,commitUrl:r.url,commitSha:r.sha})}
if(path==='/cms/publish'&&request.method==='POST')return json({ok:true,...await publishAll(env,await body(request))});
if(path==='/cms/undo'&&request.method==='POST')return json({ok:true,...await undoLast(env)});
if(path==='/health/full'&&request.method==='GET')return json(await health(env));
if(path==='/library'&&request.method==='GET')return json({ok:true,items:await library(env)});
if(path==='/library'&&request.method==='POST')return json({ok:true,...await addLibrary(env,await body(request))});
if(path==='/presets'&&request.method==='GET')return json({ok:true,presets:await presets(env)});
if(path==='/presets'&&request.method==='POST'){const p=await body(request);if(p.action==='apply')return json({ok:true,...await applyPreset(env,p.id)});if(p.action==='delete')return json({ok:true,...await deletePreset(env,p.id)});return json({ok:true,...await savePreset(env,p)})}
if(path==='/schedule'&&request.method==='GET')return json({ok:true,jobs:await schedules(env)});
if(path==='/schedule'&&request.method==='POST'){const p=await body(request);return p.action==='delete'?json({ok:true,...await deleteSchedule(env,p.id)}):json({ok:true,job:await addSchedule(env,p)})}
if(path==='/backup/export'&&request.method==='GET')return json({ok:true,backup:await exportBackup(env)});
if(path==='/backup/import'&&request.method==='POST')return json({ok:true,...await importBackup(env,await body(request))});
if(path==='/logs'&&request.method==='GET')return json({ok:true,logs:await loadList(env,LOGS)});
return null}catch(error){console.error('[CMS]',error);return json({ok:false,error:error.message||'CMS operation failed.'},Number(error.status)||502)}}
