const API_VERSION='2026-03-10';
const SEO_PATH='data/site-seo.json';
const SNAPSHOTS_PATH='data/site-snapshots.json';
const MANAGED_PATHS=['assets/pfp.jpg','data/site-settings.json','assets/site-favicon.jpg','assets/site-background.jpg','assets/site-banner.jpg',SEO_PATH];
const SEO_DEFAULTS={title:'Immortal | Developer, Discord Bots & FNF Mods',description:'Immortal is a developer portfolio featuring web projects, Discord bots, FNF modding, and current work.',themeColor:'#0a0a0a',image:'https://xm5o.github.io/assets/Immortal-site-banner.png'};
function headers(env){return{Accept:'application/vnd.github+json',Authorization:`Bearer ${env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':API_VERSION,'User-Agent':'Immortal-Site-Manager'}}
function encPath(path){return String(path).split('/').map(encodeURIComponent).join('/')}
function contentUrl(env,path,ref=''){return`https://api.github.com/repos/${env.GITHUB_REPO}/contents/${encPath(path)}${ref?`?ref=${encodeURIComponent(ref)}`:''}`}
async function gh(env,url,opt={}){const r=await fetch(url,{...opt,headers:{...headers(env),...(opt.headers||{})}});const d=await r.json().catch(()=>({}));return{r,d}}
function b64Text(text){const bytes=new TextEncoder().encode(String(text));let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(s)}
function unb64Text(value){const s=atob(String(value||'').replace(/\s+/g,'')),out=new Uint8Array(s.length);for(let i=0;i<s.length;i++)out[i]=s.charCodeAt(i);return new TextDecoder().decode(out)}
async function getFile(env,path,ref=env.GITHUB_BRANCH,missing=false){const{r,d}=await gh(env,contentUrl(env,path,ref));if(missing&&r.status===404)return null;if(!r.ok||!d.sha)throw new Error(d.message||`Could not read ${path} (${r.status}).`);return d}
async function putText(env,path,text,message){const cur=await getFile(env,path,env.GITHUB_BRANCH,true);const body={message,content:b64Text(text),branch:env.GITHUB_BRANCH};if(cur)body.sha=cur.sha;const{r,d}=await gh(env,contentUrl(env,path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(d.message||`Could not update ${path} (${r.status}).`);return d}
async function copyFile(env,path,ref,message){const old=await getFile(env,path,ref,true);if(!old)return null;let content=old.content;if(!content&&old.download_url){const response=await fetch(old.download_url,{cache:'no-store'});if(!response.ok)throw new Error(`Could not restore ${path}.`);const bytes=new Uint8Array(await response.arrayBuffer());let s='';for(let i=0;i<bytes.length;i+=32768)s+=String.fromCharCode(...bytes.subarray(i,i+32768));content=btoa(s)}const cur=await getFile(env,path,env.GITHUB_BRANCH,true);const body={message,content:String(content||'').replace(/\s+/g,''),branch:env.GITHUB_BRANCH};if(cur)body.sha=cur.sha;const{r,d}=await gh(env,contentUrl(env,path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(d.message||`Could not restore ${path} (${r.status}).`);return d}
function clean(value,max,fallback=''){const text=String(value??'').replace(/\s+/g,' ').trim();return(text||fallback).slice(0,max)}
function escAttr(value){return String(value).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function escText(value){return String(value).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function normalizeSeo(input={}){let image=SEO_DEFAULTS.image;try{const u=new URL(String(input.image||SEO_DEFAULTS.image));if(u.protocol==='https:')image=u.href.slice(0,500)}catch{}const color=/^#[0-9a-f]{6}$/i.test(String(input.themeColor||''))?String(input.themeColor).toLowerCase():SEO_DEFAULTS.themeColor;return{title:clean(input.title,90,SEO_DEFAULTS.title),description:clean(input.description,180,SEO_DEFAULTS.description),themeColor:color,image,updatedAt:new Date().toISOString()}}
async function readSeo(env,ref=env.GITHUB_BRANCH){const file=await getFile(env,SEO_PATH,ref,true);if(!file)return{...SEO_DEFAULTS};try{return normalizeSeo(JSON.parse(unb64Text(file.content||'')))}catch{return{...SEO_DEFAULTS}}}
function replace(html,re,value){return re.test(html)?html.replace(re,value):html}
async function applySeo(env,seo,message='Update site SEO metadata'){const file=await getFile(env,'index.html');let html=unb64Text(file.content||'');const title=escText(seo.title),attr=escAttr(seo.title),desc=escAttr(seo.description),color=escAttr(seo.themeColor),image=escAttr(seo.image);html=replace(html,/<title>[\s\S]*?<\/title>/i,`<title>${title}</title>`);html=replace(html,/<meta\s+name=["']description["'][^>]*>/i,`<meta name="description" content="${desc}" />`);html=replace(html,/<meta\s+name=["']theme-color["'][^>]*>/i,`<meta name="theme-color" content="${color}" />`);html=replace(html,/<meta\s+property=["']og:title["'][^>]*>/i,`<meta property="og:title" content="${attr}" />`);html=replace(html,/<meta\s+property=["']og:description["'][^>]*>/i,`<meta property="og:description" content="${desc}" />`);html=replace(html,/<meta\s+property=["']og:image["'][^>]*>/i,`<meta property="og:image" content="${image}" />`);html=replace(html,/<meta\s+name=["']twitter:title["'][^>]*>/i,`<meta name="twitter:title" content="${attr}" />`);html=replace(html,/<meta\s+name=["']twitter:description["'][^>]*>/i,`<meta name="twitter:description" content="${desc}" />`);html=replace(html,/<meta\s+name=["']twitter:image["'][^>]*>/i,`<meta name="twitter:image" content="${image}" />`);const body={message,content:b64Text(html),branch:env.GITHUB_BRANCH,sha:file.sha};const{r,d}=await gh(env,contentUrl(env,'index.html'),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error(d.message||`Could not update static SEO (${r.status}).`);return d}
async function activity(env){const q=new URLSearchParams({sha:env.GITHUB_BRANCH,per_page:'60'}),{r,d}=await gh(env,`https://api.github.com/repos/${env.GITHUB_REPO}/commits?${q}`);if(!r.ok||!Array.isArray(d))throw new Error(d.message||'Could not load site activity.');const prefixes=['Update site profile picture','Restore profile picture','Update managed site','Update site SEO','Create site snapshot','Restore site snapshot'];return d.map(c=>({sha:c.sha,shortSha:String(c.sha||'').slice(0,7),message:c.commit?.message?.split('\n')[0]||'Site update',date:c.commit?.committer?.date||null,commitUrl:c.html_url||null})).filter(x=>prefixes.some(p=>x.message.startsWith(p))).slice(0,30)}
async function readSnapshots(env){const file=await getFile(env,SNAPSHOTS_PATH,env.GITHUB_BRANCH,true);if(!file)return{items:[],sha:null};try{const items=JSON.parse(unb64Text(file.content||''));return{items:Array.isArray(items)?items.slice(0,20):[],sha:file.sha}}catch{return{items:[],sha:file.sha}}}
async function headSha(env){const{r,d}=await gh(env,`https://api.github.com/repos/${env.GITHUB_REPO}/commits/${encodeURIComponent(env.GITHUB_BRANCH)}`);if(!r.ok||!d.sha)throw new Error(d.message||'Could not resolve branch head.');return d.sha}
async function makeSnapshot(env,label){const head=await headSha(env),cur=await readSnapshots(env),item={id:crypto.randomUUID(),label:clean(label,60,`Snapshot ${new Date().toISOString().slice(0,10)}`),sha:head,createdAt:new Date().toISOString()},items=[item,...cur.items.filter(x=>x.sha!==head)].slice(0,20);await putText(env,SNAPSHOTS_PATH,`${JSON.stringify(items,null,2)}\n`,`Create site snapshot: ${item.label}`);return{item,items}}
async function restoreSnapshot(env,id){const cur=await readSnapshots(env),item=cur.items.find(x=>x.id===id);if(!item)throw Object.assign(new Error('Snapshot not found.'),{status:404});const message=`Restore site snapshot: ${item.label}`;for(const path of MANAGED_PATHS)await copyFile(env,path,item.sha,message);const seo=await readSeo(env);await applySeo(env,seo,message);return item}
async function readJson(request){const text=await request.text();if(text.length>65536)throw Object.assign(new Error('Request is too large.'),{status:413});try{return text?JSON.parse(text):{}}catch{throw Object.assign(new Error('Invalid JSON request.'),{status:400})}}
function json(data,status,origin,allowed){const h={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'};if(origin&&origin===allowed){h['Access-Control-Allow-Origin']=origin;h.Vary='Origin'}return new Response(JSON.stringify(data),{status,headers:h})}
export async function handleExtended(request,env,origin,allowed){const url=new URL(request.url);try{if(request.method==='GET'&&url.pathname==='/activity')return json({ok:true,activity:await activity(env)},200,origin,allowed);if(request.method==='GET'&&url.pathname==='/seo')return json({ok:true,seo:await readSeo(env)},200,origin,allowed);if(request.method==='POST'&&url.pathname==='/seo'){const seo=normalizeSeo(await readJson(request));await putText(env,SEO_PATH,`${JSON.stringify(seo,null,2)}\n`,'Update site SEO settings');const out=await applySeo(env,seo);return json({ok:true,seo,commitUrl:out?.commit?.html_url||null},200,origin,allowed)}if(request.method==='GET'&&url.pathname==='/snapshots'){const cur=await readSnapshots(env);return json({ok:true,snapshots:cur.items},200,origin,allowed)}if(request.method==='POST'&&url.pathname==='/snapshots'){const body=await readJson(request),result=await makeSnapshot(env,body.label);return json({ok:true,snapshot:result.item,snapshots:result.items},200,origin,allowed)}if(request.method==='POST'&&url.pathname==='/snapshots/restore'){const body=await readJson(request),snapshot=await restoreSnapshot(env,String(body.id||''));return json({ok:true,snapshot},200,origin,allowed)}}catch(error){console.error('[SiteManager:extended]',error);return json({ok:false,error:error.message||'Extended site update failed.'},Number(error.status)||502,origin,allowed)}return null}
