const SESSION_MS=4*60*60*1000,STATE_MS=10*60*1000;
function b64url(bytes){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function unb64url(value){const text=String(value||'').replace(/-/g,'+').replace(/_/g,'/');const raw=atob(text+'='.repeat((4-text.length%4)%4));return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function hmac(secret,value){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(String(secret||'')),{name:'HMAC',hash:'SHA-256'},false,['sign']);return b64url(new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(String(value)))))}
async function verifySigned(secret,token){const[payload,sig]=String(token||'').split('.');if(!payload||!sig)return null;const expected=await hmac(secret,payload);if(expected.length!==sig.length)return null;let diff=0;for(let i=0;i<expected.length;i++)diff|=expected.charCodeAt(i)^sig.charCodeAt(i);if(diff)return null;try{const value=JSON.parse(new TextDecoder().decode(unb64url(payload)));if(value.exp&&Date.now()>Number(value.exp))return null;return value}catch{return null}}
async function signPayload(secret,payload){const body=b64url(new TextEncoder().encode(JSON.stringify(payload)));return`${body}.${await hmac(secret,body)}`}
function adminUrl(env){return String(env.ADMIN_ORIGIN||env.ALLOWED_ORIGIN||'https://xm5o.github.io').replace(/\/+$/,'')+'/admin/profile/'}
function callbackUrl(request){const url=new URL(request.url);return`${url.origin}/auth/github/callback`}
export function oauthReady(env){return Boolean(String(env.GITHUB_OAUTH_CLIENT_ID||'').trim()&&String(env.GITHUB_OAUTH_CLIENT_SECRET||'').trim())}
export async function verifySessionToken(env,token){const payload=await verifySigned(env.ADMIN_KEY,token);if(!payload||payload.type!=='github-admin'||payload.v!==1||!payload.login||!payload.iat||!payload.exp)return null;const now=Date.now(),issued=Number(payload.iat),expires=Number(payload.exp);if(!Number.isFinite(issued)||!Number.isFinite(expires)||issued>now+5*60*1000||expires-issued>SESSION_MS+60*1000||now>expires)return null;const allowed=String(env.GITHUB_ALLOWED_LOGIN||env.GITHUB_REPO?.split('/')[0]||'').toLowerCase();return String(payload.login).toLowerCase()===allowed?payload:null}
export async function handleOAuthPublic(request,env){const url=new URL(request.url);if(url.pathname==='/auth/config'){return new Response(JSON.stringify({ok:true,oauthReady:oauthReady(env),allowedLogin:String(env.GITHUB_ALLOWED_LOGIN||env.GITHUB_REPO?.split('/')[0]||''),fallbackKey:true,sessionHours:SESSION_MS/3600000}),{headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}})}
if(url.pathname==='/auth/github/start'){if(!oauthReady(env))return new Response('GitHub OAuth is not configured.',{status:503});const now=Date.now(),state=await signPayload(env.ADMIN_KEY,{type:'oauth-state',v:1,iat:now,exp:now+STATE_MS,nonce:crypto.randomUUID()});const target=new URL('https://github.com/login/oauth/authorize');target.searchParams.set('client_id',env.GITHUB_OAUTH_CLIENT_ID);target.searchParams.set('redirect_uri',callbackUrl(request));target.searchParams.set('scope','read:user');target.searchParams.set('state',state);return Response.redirect(target.toString(),302)}
if(url.pathname==='/auth/github/callback'){if(!oauthReady(env))return new Response('GitHub OAuth is not configured.',{status:503});const state=await verifySigned(env.ADMIN_KEY,url.searchParams.get('state'));if(!state||state.type!=='oauth-state'||state.v!==1||!state.iat||Date.now()-Number(state.iat)>STATE_MS+60*1000)return new Response('Invalid or expired OAuth state.',{status:400});const code=url.searchParams.get('code');if(!code)return new Response('GitHub did not return an authorization code.',{status:400});const tokenResponse=await fetch('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','User-Agent':'Immortal-CMS'},body:JSON.stringify({client_id:env.GITHUB_OAUTH_CLIENT_ID,client_secret:env.GITHUB_OAUTH_CLIENT_SECRET,code,redirect_uri:callbackUrl(request)})});const tokenData=await tokenResponse.json().catch(()=>({}));if(!tokenResponse.ok||!tokenData.access_token)return new Response('Could not complete GitHub OAuth.',{status:502});const userResponse=await fetch('https://api.github.com/user',{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${tokenData.access_token}`,'User-Agent':'Immortal-CMS'}});const user=await userResponse.json().catch(()=>({}));if(!userResponse.ok||!user.login)return new Response('Could not read the GitHub account.',{status:502});const allowed=String(env.GITHUB_ALLOWED_LOGIN||env.GITHUB_REPO?.split('/')[0]||'').toLowerCase();if(String(user.login).toLowerCase()!==allowed)return new Response('This GitHub account is not allowed to manage the site.',{status:403});const now=Date.now(),session=await signPayload(env.ADMIN_KEY,{type:'github-admin',v:1,login:user.login,iat:now,exp:now+SESSION_MS,nonce:crypto.randomUUID()});return Response.redirect(`${adminUrl(env)}#session=${encodeURIComponent(session)}`,302)}
return null}
