import baseWorker from './index.js';
import{handleExtended}from'./extended.js';
import{handleCms,processSchedule}from'./cms.js';
import{handleOAuthPublic,verifySessionToken,oauthReady}from'./oauth.js';
import{createLegacyBackup}from'./legacy-backup.js';
import{fullHealth}from'./health.js';
const EXTENDED=new Set(['/activity','/seo','/snapshots','/snapshots/restore']),CMS=new Set(['/settings','/cms/publish','/cms/undo','/health/full','/library','/presets','/schedule','/backup/export','/backup/import','/logs']),AUTH_FAILURES=new Map(),OAUTH_HITS=new Map();
function norm(v){return String(v||'').trim().replace(/\/+$/,'')}function security(){return{'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Permissions-Policy':'camera=(), microphone=(), geolocation=(), payment=()','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'none'; frame-ancestors 'none'; base-uri 'none'"}}function cors(origin,allowed){const h={'Access-Control-Allow-Methods':'GET,POST,OPTIONS','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Max-Age':'86400','Cache-Control':'no-store',...security()};if(origin&&origin===allowed){h['Access-Control-Allow-Origin']=origin;h.Vary='Origin'}return h}function json(data,status,origin,allowed,extra={}){return new Response(JSON.stringify(data),{status,headers:{...cors(origin,allowed),'Content-Type':'application/json; charset=utf-8',...extra}})}function bearer(r){return String(r.headers.get('Authorization')||'').match(/^Bearer\s+(.+)$/i)?.[1]?.trim()||''}function ip(r){return String(r.headers.get('CF-Connecting-IP')||r.headers.get('X-Forwarded-For')||'unknown').split(',')[0].trim()}
function hit(map,key,max,windowMs){const now=Date.now(),old=map.get(key);const item=!old||old.reset<=now?{count:0,reset:now+windowMs}:old;item.count++;map.set(key,item);if(map.size>500){for(const[k,v]of map)if(v.reset<=now)map.delete(k)}return{allowed:item.count<=max,retry:Math.max(1,Math.ceil((item.reset-now)/1000))}}
async function safeEqual(a,b){const e=new TextEncoder(),[l,r]=await Promise.all([crypto.subtle.digest('SHA-256',e.encode(String(a||''))),crypto.subtle.digest('SHA-256',e.encode(String(b||'')))]),x=new Uint8Array(l),y=new Uint8Array(r);let d=x.length^y.length;for(let i=0;i<Math.max(x.length,y.length);i++)d|=(x[i]||0)^(y[i]||0);return d===0}async function authorized(r,env){const token=bearer(r);if(!token)return false;if(await safeEqual(token,env.ADMIN_KEY))return true;return Boolean(await verifySessionToken(env,token))}function withAdminAuth(r,env){const h=new Headers(r.headers);h.set('Authorization',`Bearer ${env.ADMIN_KEY}`);return new Request(r,{headers:h})}function addHeaders(response,origin,allowed){const h=new Headers(response.headers);for(const[k,v]of Object.entries(cors(origin,allowed)))h.set(k,v);return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h})}
function needsLegacyBackup(r,path){if(r.method!=='POST')return false;return path==='/profile'||path==='/profile/restore'||path==='/settings'||path==='/seo'||path.startsWith('/asset/')}function backupLabel(path){if(path==='/profile')return'Before instant profile publish';if(path==='/profile/restore')return'Before profile history restore';if(path==='/settings')return'Before instant settings publish';if(path==='/seo')return'Before instant SEO publish';if(path.startsWith('/asset/'))return`Before instant ${path.slice(7)} publish`;return'Before instant update'}function legacyProtected(path){return path==='/auth-check'||path==='/profile'||path==='/profile/history'||path==='/profile/restore'||path==='/settings'||path.startsWith('/asset/')}
export default{async fetch(request,env){const url=new URL(request.url),origin=norm(request.headers.get('Origin')),allowed=norm(env.ALLOWED_ORIGIN),client=ip(request);if(request.method==='GET'&&url.pathname==='/health/status'){const status=await fullHealth(env);return json({...status,service:'immortal-site-manager',oauthReady:oauthReady(env)},200,origin,allowed)}if(url.pathname.startsWith('/auth/')){if(url.pathname==='/auth/github/start'||url.pathname==='/auth/github/callback'){const limit=hit(OAUTH_HITS,`${client}:${url.pathname}`,24,10*60*1000);if(!limit.allowed)return json({ok:false,error:'Too many authentication attempts. Try again shortly.'},429,origin,allowed,{'Retry-After':String(limit.retry)})}const response=await handleOAuthPublic(request,env);if(response)return addHeaders(response,origin,allowed)}if(request.method==='OPTIONS'&&(CMS.has(url.pathname)||EXTENDED.has(url.pathname))){if(!origin||origin!==allowed)return json({ok:false,error:'Origin not allowed.'},403,origin,allowed);return new Response(null,{status:204,headers:cors(origin,allowed)})}if(origin&&origin!==allowed)return json({ok:false,error:'Origin not allowed.'},403,origin,allowed);const ok=await authorized(request,env);if(!ok&&(CMS.has(url.pathname)||EXTENDED.has(url.pathname)||legacyProtected(url.pathname))){const limit=hit(AUTH_FAILURES,client,12,5*60*1000);if(!limit.allowed)return json({ok:false,error:'Too many failed admin authentication attempts. Try again shortly.'},429,origin,allowed,{'Retry-After':String(limit.retry)})}if(ok&&needsLegacyBackup(request,url.pathname)){try{await createLegacyBackup(env,backupLabel(url.pathname))}catch(error){return json({ok:false,error:`Could not create automatic backup: ${error.message}`},502,origin,allowed)}}if(CMS.has(url.pathname)||EXTENDED.has(url.pathname)){if(!ok)return json({ok:false,error:'Invalid publisher session.'},401,origin,allowed);if(url.pathname==='/health/full')return json(await fullHealth(env),200,origin,allowed);const authed=withAdminAuth(request,env),result=CMS.has(url.pathname)?await handleCms(authed,env):await handleExtended(authed,env,origin,allowed);return result?addHeaders(result,origin,allowed):json({ok:false,error:'Not found.'},404,origin,allowed)}if(ok&&!(await safeEqual(bearer(request),env.ADMIN_KEY)))return addHeaders(await baseWorker.fetch(withAdminAuth(request,env),env),origin,allowed);return addHeaders(await baseWorker.fetch(request,env),origin,allowed)},async scheduled(controller,env,ctx){ctx.waitUntil(processSchedule(env))}};
