const $ = id => document.getElementById(id);
const currentImage=$('currentImage'),currentPalette=$('currentPalette'),imageInput=$('imageInput'),emptyEditor=$('emptyEditor'),cropEditor=$('cropEditor'),cropStage=$('cropStage'),cropCanvas=$('cropCanvas'),cropContext=cropCanvas.getContext('2d',{willReadFrequently:true}),zoomRange=$('zoomRange'),resetCrop=$('resetCrop'),centerCrop=$('centerCrop'),newPalette=$('newPalette'),previewStatus=$('previewStatus'),sitePreview=$('sitePreview'),previewProfile=$('previewProfile'),beforeImage=$('beforeImage'),afterImage=$('afterImage'),publishStatus=$('publishStatus'),refreshCurrent=$('refreshCurrent'),publishButton=$('publishButton'),publisherSetup=$('publisherSetup'),publisherConnected=$('publisherConnected'),publisherUrl=$('publisherUrl'),publisherKey=$('publisherKey'),savePublisherButton=$('savePublisherButton'),forgetPublisherButton=$('forgetPublisherButton'),publisherHost=$('publisherHost'),setupStatus=$('setupStatus'),connectionState=$('connectionState'),commitLink=$('commitLink'),deployState=$('deployState'),deployDetail=$('deployDetail'),historyList=$('historyList'),refreshHistory=$('refreshHistory'),bioInput=$('bioInput'),statusInput=$('statusInput'),commissionOpen=$('commissionOpen'),commissionTotal=$('commissionTotal'),commissionUsed=$('commissionUsed'),backgroundEnabled=$('backgroundEnabled'),bannerEnabled=$('bannerEnabled'),faviconEnabled=$('faviconEnabled'),saveSettingsButton=$('saveSettingsButton'),settingsStatus=$('settingsStatus'),previewBio=$('previewBio'),previewSiteStatus=$('previewSiteStatus'),previewCommission=$('previewCommission');
const CANVAS_SIZE=720,MAX_SOURCE_SIZE=18*1024*1024,DEFAULT_PUBLISHER_URL='https://xm5o-github-io.eminem13981398.workers.dev',PUBLISHER_URL_KEY='immortalProfilePublisherUrl',PUBLISHER_KEY_KEY='immortalProfilePublisherKey',allowedTypes=new Set(['image/jpeg','image/png','image/webp']);
const themeEngine=window.ProfilePictureTheme?new window.ProfilePictureTheme('[data-profile-theme-source-never]'):null;
const state={sourceImage:null,sourceUrl:'',baseScale:1,zoom:1,offsetX:0,offsetY:0,dragging:false,pointerId:null,dragStartX:0,dragStartY:0,dragOffsetX:0,dragOffsetY:0,palette:null,currentPalette:null,previewTimer:null,publisherReady:false,pointers:new Map(),pinchStartDistance:0,pinchStartZoom:1,settings:null};
function safeGet(key){try{return localStorage.getItem(key)||''}catch{return''}}function safeSet(key,value){try{if(value)localStorage.setItem(key,value);else localStorage.removeItem(key)}catch{}}
function normalizePublisherUrl(value){const raw=String(value||'').trim();if(!raw)return'';try{const url=new URL(raw);if(url.protocol!=='https:')return'';url.search='';url.hash='';return url.href.replace(/\/+$/,'')}catch{return''}}
function storedPublisher(){return{url:normalizePublisherUrl(safeGet(PUBLISHER_URL_KEY)||DEFAULT_PUBLISHER_URL),key:String(safeGet(PUBLISHER_KEY_KEY)).trim()}}
function setConnectionState(ready,host=''){state.publisherReady=ready;connectionState.dataset.state=ready?'online':'offline';connectionState.querySelector('strong').textContent=ready?'Direct publisher ready':'Publisher not configured';publisherSetup.hidden=ready;publisherConnected.hidden=!ready;publisherHost.textContent=ready?host:'';saveSettingsButton.disabled=!ready;updatePublishState()}
function setPublishStatus(message,type=''){publishStatus.textContent=message;publishStatus.classList.remove('success','error');if(type)publishStatus.classList.add(type)}function setSetupStatus(message,type=''){setupStatus.textContent=message;setupStatus.classList.remove('success','error');if(type)setupStatus.classList.add(type)}function setSettingsStatus(message,type=''){settingsStatus.textContent=message;settingsStatus.classList.remove('success','error');if(type)settingsStatus.classList.add(type)}
function setDeployState(mode,title,detail){deployState.dataset.state=mode;deployState.querySelector('strong').textContent=title;deployDetail.textContent=detail}
async function publisherRequest(path,options={}){const config=storedPublisher();if(!config.url||!config.key)throw new Error('Publisher connection is not configured.');const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),options.timeout||15000);try{const response=await fetch(`${config.url}${path}`,{method:options.method||'GET',headers:{Authorization:`Bearer ${config.key}`,...(options.headers||{})},body:options.body,cache:'no-store',signal:controller.signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`${response.status} ${response.statusText}`);return payload}finally{clearTimeout(timeout)}}
async function verifyPublisherConnection(){const config=storedPublisher();if(!config.url||!config.key){setConnectionState(false);return false}try{await publisherRequest('/auth-check');setConnectionState(true,new URL(config.url).host);await Promise.allSettled([loadHistory(),loadSettings()]);return true}catch(error){setConnectionState(false);publisherUrl.value=config.url||DEFAULT_PUBLISHER_URL;publisherKey.value=config.key;setSetupStatus(error.name==='AbortError'?'The publisher did not answer in time.':error.message||'Could not verify the publisher.','error');return false}}
savePublisherButton.addEventListener('click',async()=>{const url=normalizePublisherUrl(publisherUrl.value||DEFAULT_PUBLISHER_URL),key=String(publisherKey.value||'').trim();if(!url){setSetupStatus('The Cloudflare publisher URL is invalid.','error');return}if(key.length<16){setSetupStatus('Enter your private publisher key.','error');publisherKey.focus();return}savePublisherButton.disabled=true;savePublisherButton.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Checking...';safeSet(PUBLISHER_URL_KEY,url);safeSet(PUBLISHER_KEY_KEY,key);const ok=await verifyPublisherConnection();if(ok){publisherUrl.value=DEFAULT_PUBLISHER_URL;publisherKey.value='';setSetupStatus('');setPublishStatus(state.sourceImage?'Publisher ready. Click Update profile picture when the preview looks right.':'Publisher ready. Choose a new image to continue.','success')}savePublisherButton.disabled=false;savePublisherButton.innerHTML='<i class="bx bx-link"></i> Save publisher connection'});
forgetPublisherButton.addEventListener('click',()=>{safeSet(PUBLISHER_URL_KEY,'');safeSet(PUBLISHER_KEY_KEY,'');setConnectionState(false);publisherUrl.value=DEFAULT_PUBLISHER_URL;publisherKey.value='';historyList.innerHTML='<div class="history-empty">Connect the publisher to load profile history.</div>';setSetupStatus('Publisher connection removed from this device.');setPublishStatus('Publisher setup is required before updating the live site.')});
function rgbText(c){return`${c.r}, ${c.g}, ${c.b}`}function paletteFrom(el){if(!themeEngine||!el)return null;try{const dominant=themeEngine.getDominantColor(el);return dominant?themeEngine.buildPalette(dominant):null}catch(error){console.warn('[Site Manager] Palette error:',error);return null}}function paletteHex(p){if(!p||!themeEngine)return null;return{main:themeEngine.toHex(p.main),secondary:themeEngine.toHex(p.secondary),accent:themeEngine.toHex(p.accent)}}
function renderPalette(container,palette){const colors=paletteHex(palette);if(!colors){container.innerHTML='<span class="swatch"><span>No colors yet</span></span>';return}container.innerHTML=[['Main',colors.main],['Secondary',colors.secondary],['Accent',colors.accent]].map(([label,hex])=>`<span class="swatch" title="${label}: ${hex}"><span class="swatch-dot" style="background:${hex}"></span><span>${hex}</span></span>`).join('')}
function applyPreviewPalette(palette){const colors=paletteHex(palette);if(!colors)return;sitePreview.style.setProperty('--main-color',colors.main);sitePreview.style.setProperty('--secondary-color',colors.secondary);sitePreview.style.setProperty('--accent-color',colors.accent);sitePreview.style.setProperty('--preview-main-rgb',rgbText(palette.main))}
function refreshCurrentPalette(){if(!currentImage.complete||!currentImage.naturalWidth)return;state.currentPalette=paletteFrom(currentImage);renderPalette(currentPalette,state.currentPalette);if(!state.palette&&state.currentPalette)applyPreviewPalette(state.currentPalette);beforeImage.src=currentImage.src}
function loadCurrentImage(){const url=`../../assets/pfp.jpg?v=${Date.now()}`;currentImage.src=url;beforeImage.src=url}currentImage.addEventListener('load',refreshCurrentPalette);if(currentImage.complete)refreshCurrentPalette();refreshCurrent.addEventListener('click',loadCurrentImage);
function clearSourceUrl(){if(state.sourceUrl)URL.revokeObjectURL(state.sourceUrl);state.sourceUrl=''}function coverScale(image){return Math.max(CANVAS_SIZE/image.naturalWidth,CANVAS_SIZE/image.naturalHeight)}function clampOffsets(){if(!state.sourceImage)return;const scale=state.baseScale*state.zoom,width=state.sourceImage.naturalWidth*scale,height=state.sourceImage.naturalHeight*scale,maxX=Math.max(0,(width-CANVAS_SIZE)/2),maxY=Math.max(0,(height-CANVAS_SIZE)/2);state.offsetX=Math.min(maxX,Math.max(-maxX,state.offsetX));state.offsetY=Math.min(maxY,Math.max(-maxY,state.offsetY))}
function renderCrop({updatePreview=false}={}){if(!state.sourceImage)return;clampOffsets();const scale=state.baseScale*state.zoom,width=state.sourceImage.naturalWidth*scale,height=state.sourceImage.naturalHeight*scale,x=(CANVAS_SIZE-width)/2+state.offsetX,y=(CANVAS_SIZE-height)/2+state.offsetY;cropContext.clearRect(0,0,CANVAS_SIZE,CANVAS_SIZE);cropContext.fillStyle='#080808';cropContext.fillRect(0,0,CANVAS_SIZE,CANVAS_SIZE);cropContext.drawImage(state.sourceImage,x,y,width,height);if(updatePreview)scheduleThemePreview()}
function resetCropState(){if(!state.sourceImage)return;state.baseScale=coverScale(state.sourceImage);state.zoom=1;state.offsetX=0;state.offsetY=0;zoomRange.value='1';renderCrop({updatePreview:true})}function centerCropState(){if(!state.sourceImage)return;state.offsetX=0;state.offsetY=0;renderCrop({updatePreview:true})}resetCrop.addEventListener('click',resetCropState);centerCrop.addEventListener('click',centerCropState);
function scheduleThemePreview(){clearTimeout(state.previewTimer);state.previewTimer=setTimeout(updateThemePreview,80)}function updateThemePreview(){if(!state.sourceImage)return;state.palette=paletteFrom(cropCanvas);renderPalette(newPalette,state.palette);applyPreviewPalette(state.palette);const data=cropCanvas.toDataURL('image/jpeg',.86);previewProfile.src=data;afterImage.src=data;previewStatus.textContent=state.palette?'Matches live theme':'Could not read colors';updatePublishState()}
async function loadSelectedFile(file){if(!file)return;if(!allowedTypes.has(file.type)){setPublishStatus('Use a JPG, PNG, or WebP image.','error');return}if(file.size>MAX_SOURCE_SIZE){setPublishStatus('That image is too large. Choose an image under 18 MB.','error');return}clearSourceUrl();const url=URL.createObjectURL(file);state.sourceUrl=url;const image=new Image();image.decoding='async';image.onload=()=>{state.sourceImage=image;emptyEditor.hidden=true;cropEditor.hidden=false;resetCropState();setPublishStatus(state.publisherReady?'Preview ready. Click Update profile picture when it looks right.':'Preview ready. Finish the publisher setup first.')};image.onerror=()=>{setPublishStatus('Could not open that image.','error');clearSourceUrl()};image.src=url}imageInput.addEventListener('change',()=>loadSelectedFile(imageInput.files?.[0]));
zoomRange.addEventListener('input',()=>{state.zoom=Math.max(1,Math.min(3,Number(zoomRange.value)||1));renderCrop()});zoomRange.addEventListener('change',()=>renderCrop({updatePreview:true}));
function pointerDistance(){const pts=[...state.pointers.values()];if(pts.length<2)return 0;return Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
cropStage.addEventListener('pointerdown',event=>{if(!state.sourceImage)return;state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});cropStage.setPointerCapture?.(event.pointerId);if(state.pointers.size===1){state.dragging=true;state.pointerId=event.pointerId;state.dragStartX=event.clientX;state.dragStartY=event.clientY;state.dragOffsetX=state.offsetX;state.dragOffsetY=state.offsetY}else if(state.pointers.size===2){state.dragging=false;state.pinchStartDistance=pointerDistance();state.pinchStartZoom=state.zoom}});
cropStage.addEventListener('pointermove',event=>{if(!state.pointers.has(event.pointerId))return;state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(state.pointers.size>=2){const d=pointerDistance();if(state.pinchStartDistance>0){state.zoom=Math.max(1,Math.min(3,state.pinchStartZoom*(d/state.pinchStartDistance)));zoomRange.value=String(state.zoom);renderCrop()}return}if(!state.dragging||event.pointerId!==state.pointerId)return;const rect=cropCanvas.getBoundingClientRect(),scale=CANVAS_SIZE/rect.width;state.offsetX=state.dragOffsetX+(event.clientX-state.dragStartX)*scale;state.offsetY=state.dragOffsetY+(event.clientY-state.dragStartY)*scale;renderCrop()});
function finishPointer(event){if(state.pointers.has(event.pointerId))state.pointers.delete(event.pointerId);cropStage.releasePointerCapture?.(event.pointerId);if(state.pointers.size===1){const [id,p]=state.pointers.entries().next().value;state.dragging=true;state.pointerId=id;state.dragStartX=p.x;state.dragStartY=p.y;state.dragOffsetX=state.offsetX;state.dragOffsetY=state.offsetY}else{state.dragging=false;state.pointerId=null;if(state.pointers.size===0)renderCrop({updatePreview:true})}}cropStage.addEventListener('pointerup',finishPointer);cropStage.addEventListener('pointercancel',finishPointer);
function updatePublishState(){publishButton.disabled=!(state.publisherReady&&state.sourceImage&&state.palette)}function exportBlob(){return new Promise((resolve,reject)=>cropCanvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not prepare the JPEG image.')),'image/jpeg',.9))}
async function sha256(blob){const digest=await crypto.subtle.digest('SHA-256',await blob.arrayBuffer());return[...new Uint8Array(digest)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function waitForLiveHash(expectedHash,timeoutMs=120000){setDeployState('working','Waiting for GitHub Pages','Checking the live image for the new version…');const started=Date.now();while(Date.now()-started<timeoutMs){try{const response=await fetch(`../../assets/pfp.jpg?live=${Date.now()}`,{cache:'no-store'});if(response.ok){const liveHash=await sha256(await response.blob());if(liveHash===expectedHash){setDeployState('live','Live on the website','GitHub Pages is serving the new profile picture.');loadCurrentImage();return true}}}catch{}await new Promise(r=>setTimeout(r,5000))}setDeployState('error','Commit published, Pages still pending','The GitHub commit succeeded, but the live cache has not caught up yet.');return false}
publishButton.addEventListener('click',async()=>{if(publishButton.disabled)return;publishButton.disabled=true;publishButton.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Updating...';commitLink.hidden=true;setPublishStatus('Publishing the new profile picture directly to GitHub...');try{const blob=await exportBlob(),expectedHash=await sha256(blob),result=await publisherRequest('/profile',{method:'POST',timeout:30000,headers:{'Content-Type':'image/jpeg'},body:blob});const localPreview=cropCanvas.toDataURL('image/jpeg',.9);currentImage.src=localPreview;beforeImage.src=localPreview;state.currentPalette=state.palette;renderPalette(currentPalette,state.currentPalette);setPublishStatus('GitHub commit created. Waiting for the live site…','success');if(result.commitUrl){commitLink.href=result.commitUrl;commitLink.hidden=false}loadHistory().catch(()=>{});waitForLiveHash(expectedHash).catch(()=>{})}catch(error){setDeployState('error','Publish failed','The live site was not changed.');setPublishStatus(error.name==='AbortError'?'The publisher timed out. Check the Worker and try again.':error.message||'Could not update the profile picture.','error')}finally{publishButton.innerHTML='<i class="bx bx-upload"></i> Update profile picture';updatePublishState()}});
function formatDate(value){if(!value)return'Unknown time';try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return value}}
async function loadHistory(){if(!state.publisherReady)return;historyList.innerHTML='<div class="history-empty">Loading history…</div>';try{const result=await publisherRequest('/profile/history?limit=10',{timeout:20000}),items=result.history||[];historyList.replaceChildren();if(!items.length){historyList.innerHTML='<div class="history-empty">No profile history yet.</div>';return}items.forEach((item,index)=>{const row=document.createElement('div');row.className='history-item';const img=document.createElement('img');img.src=`${item.thumbnailUrl}?v=${item.shortSha}`;img.alt='Previous profile picture';const copy=document.createElement('div');copy.className='history-copy';const strong=document.createElement('strong');strong.textContent=index===0?`Current · ${item.message}`:item.message;const small=document.createElement('small');small.textContent=`${formatDate(item.date)} · ${item.shortSha}`;copy.append(strong,small);const actions=document.createElement('div');actions.className='history-actions';if(index>0){const restore=document.createElement('button');restore.type='button';restore.textContent='Restore';restore.addEventListener('click',()=>restoreHistory(item,restore));actions.append(restore)}const open=document.createElement('a');open.href=item.commitUrl||'#';open.target='_blank';open.rel='noopener noreferrer';open.textContent='Commit';actions.append(open);row.append(img,copy,actions);historyList.append(row)})}catch(error){historyList.innerHTML='';const empty=document.createElement('div');empty.className='history-empty';empty.textContent=error.message||'Could not load history.';historyList.append(empty)}}refreshHistory.addEventListener('click',()=>loadHistory());
async function restoreHistory(item,button){if(!confirm(`Restore profile picture from ${formatDate(item.date)}?`))return;button.disabled=true;button.textContent='Restoring…';setDeployState('working','Restoring previous picture','Creating a new GitHub commit from the selected revision…');try{let expectedHash='';try{const r=await fetch(`${item.thumbnailUrl}?restore=${Date.now()}`,{cache:'no-store'});if(r.ok)expectedHash=await sha256(await r.blob())}catch{}const result=await publisherRequest('/profile/restore',{method:'POST',timeout:30000,headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:item.sha})});if(result.commitUrl){commitLink.href=result.commitUrl;commitLink.hidden=false}setPublishStatus('Previous profile picture restored in GitHub.','success');await loadHistory();if(expectedHash)waitForLiveHash(expectedHash).catch(()=>{});else{setDeployState('working','Restore committed','Refresh the page shortly to see it live.');setTimeout(loadCurrentImage,12000)}}catch(error){setDeployState('error','Restore failed','GitHub was not changed.');setPublishStatus(error.message||'Could not restore that profile picture.','error')}finally{button.disabled=false;button.textContent='Restore'}}
function renderSettingsPreview(){previewBio.textContent=bioInput.value.trim()||'The preview uses the same palette engine as the live website.';previewSiteStatus.textContent=statusInput.value.trim()||'Available';previewCommission.textContent=commissionOpen.checked?'Open':'Closed'}[bioInput,statusInput,commissionOpen,commissionTotal,commissionUsed,backgroundEnabled,bannerEnabled,faviconEnabled].forEach(el=>el.addEventListener('input',renderSettingsPreview));
function applySettingsToForm(s){state.settings=s;bioInput.value=s.bio||'';statusInput.value=s.statusText||'';commissionOpen.checked=Boolean(s.commissionOpen);commissionTotal.value=s.commissionTotal||4;commissionUsed.value=s.commissionUsed||0;backgroundEnabled.checked=Boolean(s.backgroundEnabled);bannerEnabled.checked=Boolean(s.bannerEnabled);faviconEnabled.checked=Boolean(s.faviconEnabled);commissionUsed.max=String(s.commissionTotal||4);renderSettingsPreview()}
commissionTotal.addEventListener('input',()=>{commissionUsed.max=String(Math.max(1,Number(commissionTotal.value)||1));if(Number(commissionUsed.value)>Number(commissionUsed.max))commissionUsed.value=commissionUsed.max});
async function loadSettings(){if(!state.publisherReady)return;setSettingsStatus('Loading site settings…');try{const result=await publisherRequest('/settings');applySettingsToForm(result.settings||{});setSettingsStatus('')}catch(error){setSettingsStatus(error.message||'Could not load site settings.','error')}}
function collectSettings(){return{bio:bioInput.value,statusText:statusInput.value,commissionOpen:commissionOpen.checked,commissionTotal:Number(commissionTotal.value)||4,commissionUsed:Number(commissionUsed.value)||0,backgroundEnabled:backgroundEnabled.checked,bannerEnabled:bannerEnabled.checked,faviconEnabled:faviconEnabled.checked}}
async function saveSettings({silent=false}={}){if(!state.publisherReady)return false;saveSettingsButton.disabled=true;if(!silent)setSettingsStatus('Saving site settings…');try{const result=await publisherRequest('/settings',{method:'POST',timeout:30000,headers:{'Content-Type':'application/json'},body:JSON.stringify(collectSettings())});applySettingsToForm(result.settings||collectSettings());if(!silent)setSettingsStatus('Site settings saved. GitHub Pages will pick them up automatically.','success');return true}catch(error){setSettingsStatus(error.message||'Could not save site settings.','error');return false}finally{saveSettingsButton.disabled=!state.publisherReady}}saveSettingsButton.addEventListener('click',()=>saveSettings());
function fileImage(file){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Could not read that image.'))};img.src=url})}function canvasBlob(canvas,quality=.88){return new Promise((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Could not prepare that image.')),'image/jpeg',quality))}
async function prepareAsset(file,kind){if(!allowedTypes.has(file.type))throw new Error('Use a JPG, PNG, or WebP image.');if(file.size>MAX_SOURCE_SIZE)throw new Error('Choose an image under 18 MB.');const img=await fileImage(file),canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');if(kind==='favicon'){canvas.width=512;canvas.height=512;const scale=Math.max(512/img.naturalWidth,512/img.naturalHeight),w=img.naturalWidth*scale,h=img.naturalHeight*scale;ctx.drawImage(img,(512-w)/2,(512-h)/2,w,h)}else{const maxW=1600,maxH=1000,scale=Math.min(1,maxW/img.naturalWidth,maxH/img.naturalHeight);canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));ctx.drawImage(img,0,0,canvas.width,canvas.height)}return canvasBlob(canvas,.88)}
document.querySelectorAll('input[data-asset]').forEach(input=>input.addEventListener('change',async()=>{const file=input.files?.[0],kind=input.dataset.asset;if(!file||!state.publisherReady)return;const label=input.closest('.asset-button');label?.classList.add('busy');setSettingsStatus(`Uploading ${kind}…`);try{const blob=await prepareAsset(file,kind);await publisherRequest(`/asset/${kind}`,{method:'POST',timeout:30000,headers:{'Content-Type':'image/jpeg'},body:blob});const toggle=$(kind+'Enabled');if(toggle)toggle.checked=true;renderSettingsPreview();await saveSettings({silent:true});setSettingsStatus(`${kind[0].toUpperCase()+kind.slice(1)} uploaded and enabled. GitHub Pages will update shortly.`,'success')}catch(error){setSettingsStatus(error.message||`Could not upload ${kind}.`,'error')}finally{label?.classList.remove('busy');input.value=''}}));
renderPalette(newPalette,null);publisherUrl.value=storedPublisher().url||DEFAULT_PUBLISHER_URL;verifyPublisherConnection();updatePublishState();renderSettingsPreview();window.addEventListener('beforeunload',clearSourceUrl);
