import {decodeImageFile,coverScale,drawCrop,canvasBlob,formatBytes} from './image-tools.js';
import {publisherRequest,isPublisherReady,onAuthChange} from './auth.js';
import {saveSettings,setAssetPreview,applyRealPreview} from './site-controls.js';
const $=id=>document.getElementById(id);
const MAX_SOURCE=30*1024*1024;
const TARGETS={favicon:{width:512,height:512,label:'1:1',title:'Prepare favicon'},background:{width:1920,height:1080,label:'16:9',title:'Prepare homepage background'},banner:{width:1600,height:900,label:'16:9',title:'Prepare hero banner'}};
const ctx=$('assetCropCanvas').getContext('2d',{willReadFrequently:true});
const state={kind:'',source:null,file:null,baseScale:1,zoom:1,offsetX:0,offsetY:0,pointers:new Map(),pinchStartDistance:0,pinchStartZoom:1,drag:null};
function setStatus(message,type=''){const el=$('settingsStatus');el.textContent=message;el.className=`settings-status${type?` ${type}`:''}`}
function render(updateInfo=false){const target=TARGETS[state.kind];if(!target||!state.source)return;drawCrop(ctx,state.source.image,state.source.width,state.source.height,state,target.width,target.height);$('assetZoomRange').value=String(state.zoom);if(updateInfo)canvasBlob($('assetCropCanvas'),.88).then(blob=>$('assetCropInfo').textContent=`${state.source.width}×${state.source.height} · ${formatBytes(state.file.size)} → ${target.width}×${target.height} · ${formatBytes(blob.size)}`).catch(()=>{})}
function distance(){const pts=[...state.pointers.values()];return pts.length<2?0:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
function bindGestures(){const stage=$('assetCropStage');stage.addEventListener('pointerdown',event=>{state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});stage.setPointerCapture?.(event.pointerId);if(state.pointers.size===1)state.drag={id:event.pointerId,x:event.clientX,y:event.clientY,ox:state.offsetX,oy:state.offsetY};else if(state.pointers.size===2){state.drag=null;state.pinchStartDistance=distance();state.pinchStartZoom=state.zoom}});stage.addEventListener('pointermove',event=>{if(!state.pointers.has(event.pointerId))return;state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(state.pointers.size>=2){const d=distance();if(state.pinchStartDistance)state.zoom=Math.max(1,Math.min(3,state.pinchStartZoom*d/state.pinchStartDistance));render(false);return}if(!state.drag||state.drag.id!==event.pointerId)return;const rect=$('assetCropCanvas').getBoundingClientRect(),scale=$('assetCropCanvas').width/rect.width;state.offsetX=state.drag.ox+(event.clientX-state.drag.x)*scale;state.offsetY=state.drag.oy+(event.clientY-state.drag.y)*scale;render(false)});const finish=event=>{state.pointers.delete(event.pointerId);stage.releasePointerCapture?.(event.pointerId);state.drag=null;if(!state.pointers.size)render(true)};stage.addEventListener('pointerup',finish);stage.addEventListener('pointercancel',finish)}
async function openCrop(kind,file){const target=TARGETS[kind];if(!target||!file)return;if(file.size>MAX_SOURCE)return setStatus('That source image is over 30 MB.','error');try{state.source?.close?.();state.source=await decodeImageFile(file);state.file=file;state.kind=kind;$('assetCropCanvas').width=target.width;$('assetCropCanvas').height=target.height;state.baseScale=coverScale(state.source.width,state.source.height,target.width,target.height);state.zoom=1;state.offsetX=0;state.offsetY=0;state.pointers.clear();$('assetCropTitle').textContent=target.title;$('assetCropRatio').textContent=`${target.label} · ${target.width}×${target.height}`;$('assetCropModal').hidden=false;render(true)}catch(error){setStatus(error.message||'Could not decode that image.','error')}}
function closeCrop(){$('assetCropModal').hidden=true}
async function upload(){if(!state.kind)return;if(!isPublisherReady())return setStatus('Unlock the publisher first.','error');const button=$('assetUploadButton');button.disabled=true;button.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Uploading…';try{const blob=await canvasBlob($('assetCropCanvas'),.88);await publisherRequest(`/asset/${state.kind}`,{method:'POST',timeout:45000,headers:{'Content-Type':'image/jpeg'},body:blob});setAssetPreview(state.kind,URL.createObjectURL(blob));if(state.kind==='favicon')$('faviconEnabled').checked=true;if(state.kind==='background')$('backgroundEnabled').checked=true;if(state.kind==='banner')$('bannerEnabled').checked=true;await saveSettings(true);closeCrop();setStatus(`${state.kind[0].toUpperCase()+state.kind.slice(1)} uploaded, compressed, and enabled.`,'success');applyRealPreview()}catch(error){setStatus(error.message||'Asset upload failed.','error')}finally{button.disabled=false;button.innerHTML='<i class="bx bx-cloud-upload"></i> Upload prepared image'}}
async function resetAsset(kind){if(kind==='favicon')$('faviconEnabled').checked=false;if(kind==='background')$('backgroundEnabled').checked=false;if(kind==='banner')$('bannerEnabled').checked=false;setAssetPreview(kind,'');try{await saveSettings(true);setStatus(`${kind[0].toUpperCase()+kind.slice(1)} reset to the site default.`,'success');applyRealPreview()}catch(error){setStatus(error.message||'Could not reset that asset.','error')}}
export function initAssetEditor(){document.querySelectorAll('[data-asset]').forEach(input=>input.addEventListener('change',()=>{openCrop(input.dataset.asset,input.files?.[0]);input.value=''}));document.querySelectorAll('[data-close-asset-modal]').forEach(el=>el.addEventListener('click',closeCrop));$('assetCenterButton').addEventListener('click',()=>{state.offsetX=0;state.offsetY=0;render(true)});$('assetZoomRange').addEventListener('input',()=>{state.zoom=Number($('assetZoomRange').value)||1;render(false)});$('assetZoomRange').addEventListener('change',()=>render(true));$('assetUploadButton').addEventListener('click',upload);document.querySelectorAll('[data-reset-asset]').forEach(button=>button.addEventListener('click',()=>resetAsset(button.dataset.resetAsset)));bindGestures();onAuthChange(ready=>{document.querySelectorAll('.asset-button,.asset-reset').forEach(el=>{el.style.opacity=ready?'':'0.55'})});window.addEventListener('beforeunload',()=>state.source?.close?.())}
