import{decodeImageFile,coverScale,drawCrop,canvasBlob,formatBytes}from'./image-tools.js';
import{publisherRequest,isPublisherReady,onAuthChange}from'./auth.js';
import{saveSettings,setAssetPreview,applyRealPreview}from'./site-controls.js';
import{clearStagedFile,isDraftMode,stageFile}from'./draft.js';
const $=id=>document.getElementById(id),MAX_SOURCE=30*1024*1024,TARGETS={favicon:{width:512,height:512,label:'1:1',title:'Prepare favicon',path:'assets/site-favicon.jpg'},background:{width:1920,height:1080,label:'16:9',title:'Prepare homepage background',path:'assets/site-background.jpg'},banner:{width:1600,height:900,label:'16:9',title:'Prepare hero banner',path:'assets/site-banner.jpg'}},ctx=$('assetCropCanvas').getContext('2d',{willReadFrequently:true});
const state={kind:'',source:null,file:null,baseScale:1,zoom:1,offsetX:0,offsetY:0,pointers:new Map(),pinchStartDistance:0,pinchStartZoom:1,drag:null};
function setStatus(m,t=''){const e=$('settingsStatus');e.textContent=m;e.className=`settings-status${t?` ${t}`:''}`}function render(info=false){const t=TARGETS[state.kind];if(!t||!state.source)return;drawCrop(ctx,state.source.image,state.source.width,state.source.height,state,t.width,t.height);$('assetZoomRange').value=String(state.zoom);if(info)canvasBlob($('assetCropCanvas'),.88).then(blob=>$('assetCropInfo').textContent=`${state.source.width}×${state.source.height} · ${formatBytes(state.file.size)} → ${t.width}×${t.height} · ${formatBytes(blob.size)}`).catch(()=>{})}
function distance(){const p=[...state.pointers.values()];return p.length<2?0:Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y)}function bindGestures(){const s=$('assetCropStage');s.addEventListener('pointerdown',e=>{state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});s.setPointerCapture?.(e.pointerId);if(state.pointers.size===1)state.drag={id:e.pointerId,x:e.clientX,y:e.clientY,ox:state.offsetX,oy:state.offsetY};else if(state.pointers.size===2){state.drag=null;state.pinchStartDistance=distance();state.pinchStartZoom=state.zoom}});s.addEventListener('pointermove',e=>{if(!state.pointers.has(e.pointerId))return;state.pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(state.pointers.size>=2){const d=distance();if(state.pinchStartDistance)state.zoom=Math.max(1,Math.min(3,state.pinchStartZoom*d/state.pinchStartDistance));render();return}if(!state.drag||state.drag.id!==e.pointerId)return;const r=$('assetCropCanvas').getBoundingClientRect(),scale=$('assetCropCanvas').width/r.width;state.offsetX=state.drag.ox+(e.clientX-state.drag.x)*scale;state.offsetY=state.drag.oy+(e.clientY-state.drag.y)*scale;render()});const end=e=>{state.pointers.delete(e.pointerId);s.releasePointerCapture?.(e.pointerId);state.drag=null;if(!state.pointers.size)render(true)};s.addEventListener('pointerup',end);s.addEventListener('pointercancel',end)}
async function openCrop(kind,file){const t=TARGETS[kind];if(!t||!file)return;if(file.size>MAX_SOURCE)return setStatus('That source image is over 30 MB.','error');try{state.source?.close?.();state.source=await decodeImageFile(file);state.file=file;state.kind=kind;$('assetCropCanvas').width=t.width;$('assetCropCanvas').height=t.height;state.baseScale=coverScale(state.source.width,state.source.height,t.width,t.height);state.zoom=1;state.offsetX=0;state.offsetY=0;state.pointers.clear();$('assetCropTitle').textContent=t.title;$('assetCropRatio').textContent=`${t.label} · ${t.width}×${t.height}`;$('assetCropModal').hidden=false;render(true);syncUploadButton()}catch(e){setStatus(e.message||'Could not decode that image.','error')}}function closeCrop(){$('assetCropModal').hidden=true}
function enableKind(kind){const e=$(`${kind}Enabled`);if(e)e.checked=true}
async function upload(){if(!state.kind)return;if(!isPublisherReady())return setStatus('Unlock the publisher first.','error');const b=$('assetUploadButton'),target=TARGETS[state.kind];b.disabled=true;b.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Preparing…';try{const blob=await canvasBlob($('assetCropCanvas'),.88);if(isDraftMode()){stageFile(target.path,blob,`${state.kind[0].toUpperCase()+state.kind.slice(1)} image`);setAssetPreview(state.kind,URL.createObjectURL(blob));enableKind(state.kind);await saveSettings(true);closeCrop();setStatus(`${state.kind[0].toUpperCase()+state.kind.slice(1)} staged for Publish All.`,'success');applyRealPreview();return}await publisherRequest(`/asset/${state.kind}`,{method:'POST',timeout:45000,headers:{'Content-Type':'image/jpeg'},body:blob});setAssetPreview(state.kind,URL.createObjectURL(blob));enableKind(state.kind);await saveSettings(true);closeCrop();setStatus(`${state.kind[0].toUpperCase()+state.kind.slice(1)} uploaded and enabled.`,'success');applyRealPreview()}catch(e){setStatus(e.message||'Asset update failed.','error')}finally{b.disabled=false;syncUploadButton()}}
async function resetAsset(kind){const t=TARGETS[kind];$(`${kind}Enabled`).checked=false;setAssetPreview(kind,'');clearStagedFile(t.path);try{await saveSettings(true);setStatus(`${kind[0].toUpperCase()+kind.slice(1)} reset to the site default${isDraftMode()?' in the draft':''}.`,'success');applyRealPreview()}catch(e){setStatus(e.message||'Could not reset that asset.','error')}}
function syncUploadButton(){const b=$('assetUploadButton');if(!b)return;b.innerHTML=isDraftMode()?'<i class="bx bx-layer-plus"></i> Stage prepared image':'<i class="bx bx-cloud-upload"></i> Upload prepared image'}
export function initAssetEditor(){document.querySelectorAll('[data-asset]').forEach(input=>input.addEventListener('change',()=>{openCrop(input.dataset.asset,input.files?.[0]);input.value=''}));document.querySelectorAll('[data-close-asset-modal]').forEach(el=>el.addEventListener('click',closeCrop));$('assetCenterButton').addEventListener('click',()=>{state.offsetX=0;state.offsetY=0;render(true)});$('assetZoomRange').addEventListener('input',()=>{state.zoom=Number($('assetZoomRange').value)||1;render()});$('assetZoomRange').addEventListener('change',()=>render(true));$('assetUploadButton').addEventListener('click',upload);document.querySelectorAll('[data-reset-asset]').forEach(b=>b.addEventListener('click',()=>resetAsset(b.dataset.resetAsset)));bindGestures();window.addEventListener('immortal:draft-change',syncUploadButton);onAuthChange(ready=>{document.querySelectorAll('.asset-button,.asset-reset').forEach(el=>{el.style.opacity=ready?'':'0.55'})});window.addEventListener('beforeunload',()=>state.source?.close?.());syncUploadButton()}
