const DEFAULT_URL='https://xm5o-github-io.eminem13981398.workers.dev';
const URL_KEY='immortalProfilePublisherUrl',LOCAL_KEY='immortalProfilePublisherKey',SESSION_KEY='immortalProfilePublisherSessionKey',OAUTH_KEY='immortalGithubAdminSession',REMEMBER_KEY='immortalProfilePublisherRemember';
const AUTO_LOCK_MS=15*60*1000;let publisherKey='',ready=false,lockTimer=null,mode='key';const listeners=new Set();const $=id=>document.getElementById(id);
function getLocal(k){try{return localStorage.getItem(k)||''}catch{return''}}function setLocal(k,v){try{v?localStorage.setItem(k,v):localStorage.removeItem(k)}catch{}}function getSession(k){try{return sessionStorage.getItem(k)||''}catch{return''}}function setSession(k,v){try{v?sessionStorage.setItem(k,v):sessionStorage.removeItem(k)}catch{}}
function normalizeUrl(v){try{const u=new URL(String(v||'').trim());return u.protocol==='https:'?u.href.replace(/\/+$/,''):''}catch{return''}}function notify(){for(const f of listeners)f(ready)}
function setUi(message=''){const setup=$('publisherSetup'),connected=$('publisherConnected'),connection=$('connectionState'),host=$('publisherHost'),modeLabel=$('authModeLabel');setup.hidden=ready;connected.hidden=!ready;connection.dataset.state=ready?'online':'offline';connection.querySelector('strong').textContent=ready?(mode==='github'?'GitHub connected':'Publisher ready'):'Publisher locked';host.textContent=ready?new URL(getPublisherUrl()).host:'';if(modeLabel)modeLabel.textContent=ready?(mode==='github'?'GitHub OAuth session':'Private publisher key'):'';['saveSettingsButton','saveSeoButton','createSnapshotButton'].forEach(id=>{const el=$(id);if(el)el.disabled=!ready});document.querySelectorAll('[data-auth-required]').forEach(el=>{el.disabled=!ready});if(message){const s=$('setupStatus');s.textContent=message;s.className=`setup-status${ready?' success':''}`}}
function resetTimer(){if(!ready)return;clearTimeout(lockTimer);lockTimer=setTimeout(()=>lockPublisher('Auto-locked after 15 minutes of inactivity.'),AUTO_LOCK_MS)}
export function getPublisherUrl(){return normalizeUrl(getLocal(URL_KEY)||DEFAULT_URL)}export function isPublisherReady(){return ready}export function getAuthMode(){return mode}export function onAuthChange(fn){listeners.add(fn);return()=>listeners.delete(fn)}
export async function publisherRequest(path,options={}){if(!ready||!publisherKey)throw new Error('Publisher is locked.');resetTimer();const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),options.timeout||20000);try{const response=await fetch(`${getPublisherUrl()}${path}`,{method:options.method||'GET',headers:{Authorization:`Bearer ${publisherKey}`,...(options.headers||{})},body:options.body,cache:'no-store',signal:controller.signal});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.error||`${response.status} ${response.statusText}`);return payload}finally{clearTimeout(timeout)}}
export function lockPublisher(message='Publisher locked for this session.'){ready=false;publisherKey='';setSession(SESSION_KEY,'');setSession(OAUTH_KEY,'');clearTimeout(lockTimer);setUi(message);notify()}
async function verifyToken(token,tokenMode){publisherKey=token;mode=tokenMode;ready=true;await publisherRequest('/auth-check');setUi(tokenMode==='github'?'Signed in with GitHub.':'Publisher unlocked.');resetTimer();notify();return true}
async function unlockKey(key,remember){const value=String(key||'').trim();if(value.length<16)throw new Error('Enter your private publisher key.');await verifyToken(value,'key');if(remember){setLocal(LOCAL_KEY,value);setLocal(REMEMBER_KEY,'1');setSession(SESSION_KEY,'')}else{setSession(SESSION_KEY,value);setLocal(LOCAL_KEY,'');setLocal(REMEMBER_KEY,'')}}
function consumeOAuthFragment(){const hash=new URLSearchParams(location.hash.replace(/^#/,'')),token=hash.get('session');if(!token)return'';setSession(OAUTH_KEY,token);history.replaceState(null,'',location.pathname+location.search);return token}
async function loadAuthConfig(){const button=$('githubLoginButton'),hint=$('oauthHint');try{const response=await fetch(`${getPublisherUrl()}/auth/config`,{cache:'no-store'}),cfg=await response.json();if(cfg.oauthReady){button.hidden=false;hint.textContent=`GitHub login is enabled for @${cfg.allowedLogin}.`;button.onclick=()=>{location.href=`${getPublisherUrl()}/auth/github/start`}}else{button.hidden=true;hint.textContent='GitHub account login is code-ready. Add GITHUB_OAUTH_CLIENT_ID and GITHUB_OAUTH_CLIENT_SECRET in Cloudflare to enable it.'}}catch{button.hidden=true}}
export async function initAuth(){const urlInput=$('publisherUrl'),keyInput=$('publisherKey'),remember=$('rememberPublisher'),button=$('savePublisherButton'),lock=$('forgetPublisherButton'),status=$('setupStatus');urlInput.value=getLocal(URL_KEY)||DEFAULT_URL;remember.checked=getLocal(REMEMBER_KEY)==='1';const oauth=consumeOAuthFragment()||getSession(OAUTH_KEY);publisherKey=oauth||getSession(SESSION_KEY)||(remember.checked?getLocal(LOCAL_KEY):'');mode=oauth?'github':'key';await loadAuthConfig();button.addEventListener('click',async()=>{const url=normalizeUrl(urlInput.value||DEFAULT_URL);if(!url){status.textContent='The Cloudflare Worker URL is invalid.';status.className='setup-status error';return}setLocal(URL_KEY,url);const value=String(keyInput.value||(remember.checked?getLocal(LOCAL_KEY):'')).trim();button.disabled=true;button.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Unlocking…';try{await unlockKey(value,remember.checked);keyInput.value=''}catch(error){ready=false;publisherKey='';setUi();status.textContent=error.message||'Could not unlock the publisher.';status.className='setup-status error'}finally{button.disabled=false;button.innerHTML='<i class="bx bx-lock-open-alt"></i> Unlock publisher'}});lock.addEventListener('click',()=>lockPublisher());['pointerdown','keydown','touchstart'].forEach(event=>window.addEventListener(event,resetTimer,{passive:true}));if(publisherKey){try{await verifyToken(publisherKey,mode);return true}catch{ready=false;publisherKey='';if(mode==='github')setSession(OAUTH_KEY,'')}}setUi();notify();return false}
