import{publisherRequest,isPublisherReady}from'./auth.js';
const MODE_KEY='immortalCmsDraftMode',DB_NAME='immortal-admin',DB_VERSION=1,STORE='state',DRAFT_KEY='draft-v1';
const listeners=new Set();
const state={enabled:true,settings:null,seo:null,files:new Map(),notes:new Map(),restored:false,updatedAt:null};
let dbPromise=null,persistTimer=null;
function readMode(){try{return localStorage.getItem(MODE_KEY)!=='0'}catch{return true}}
function saveMode(){try{localStorage.setItem(MODE_KEY,state.enabled?'1':'0')}catch{}}
function notify(){const detail=getDraftSummary();for(const fn of listeners)fn(detail);window.dispatchEvent(new CustomEvent('immortal:draft-change',{detail}))}
function openDb(){if(!('indexedDB'in window))return Promise.resolve(null);if(dbPromise)return dbPromise;dbPromise=new Promise(resolve=>{try{const request=indexedDB.open(DB_NAME,DB_VERSION);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>resolve(null);request.onblocked=()=>resolve(null)}catch{resolve(null)}});return dbPromise}
async function readPersisted(){const db=await openDb();if(!db)return null;return new Promise(resolve=>{try{const tx=db.transaction(STORE,'readonly'),request=tx.objectStore(STORE).get(DRAFT_KEY);request.onsuccess=()=>resolve(request.result||null);request.onerror=()=>resolve(null)}catch{resolve(null)}})}
async function writePersisted(record){const db=await openDb();if(!db)return;await new Promise(resolve=>{try{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(record,DRAFT_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>resolve();tx.onabort=()=>resolve()}catch{resolve()}})}
async function deletePersisted(){const db=await openDb();if(!db)return;await new Promise(resolve=>{try{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(DRAFT_KEY);tx.oncomplete=()=>resolve();tx.onerror=()=>resolve();tx.onabort=()=>resolve()}catch{resolve()}})}
function persistedRecord(){return{version:1,updatedAt:new Date().toISOString(),settings:state.settings?structuredClone(state.settings):null,seo:state.seo?structuredClone(state.seo):null,files:[...state.files].map(([path,blob])=>({path,blob,label:state.notes.get(path)||path})),notes:Object.fromEntries([...state.notes].filter(([key])=>key==='settings'||key==='seo'))}}
function persistSoon(){clearTimeout(persistTimer);persistTimer=setTimeout(async()=>{if(getDraftSummary().hasChanges)await writePersisted(persistedRecord());else await deletePersisted()},120)}
async function blob64(blob){const bytes=new Uint8Array(await blob.arrayBuffer());let out='';for(let i=0;i<bytes.length;i+=32768)out+=String.fromCharCode(...bytes.subarray(i,i+32768));return btoa(out)}
async function normalizeFiles(files=[]){const out=[];for(const item of files){if(!item?.path||!item?.blob)continue;out.push({path:item.path,base64:await blob64(item.blob)})}return out}
export async function initDraftState(){state.enabled=readMode();const saved=await readPersisted();if(saved?.version===1){state.settings=saved.settings&&typeof saved.settings==='object'?saved.settings:null;state.seo=saved.seo&&typeof saved.seo==='object'?saved.seo:null;state.files.clear();state.notes.clear();if(saved.notes?.settings)state.notes.set('settings',String(saved.notes.settings));if(saved.notes?.seo)state.notes.set('seo',String(saved.notes.seo));for(const item of Array.isArray(saved.files)?saved.files:[]){if(item?.path&&item?.blob instanceof Blob){state.files.set(item.path,item.blob);state.notes.set(item.path,String(item.label||item.path))}}state.updatedAt=saved.updatedAt||null;state.restored=Boolean(state.settings||state.seo||state.files.size)}notify();return getDraftSummary()}
export function isDraftMode(){return state.enabled}
export function setDraftMode(value){state.enabled=Boolean(value);saveMode();notify()}
export function onDraftChange(fn){listeners.add(fn);return()=>listeners.delete(fn)}
export function stageSettings(value,label='Site settings'){state.settings=structuredClone(value);state.notes.set('settings',label);state.updatedAt=new Date().toISOString();notify();persistSoon()}
export function stageSeo(value,label='SEO metadata'){state.seo=structuredClone(value);state.notes.set('seo',label);state.updatedAt=new Date().toISOString();notify();persistSoon()}
export function stageFile(path,blob,label=path){state.files.set(path,blob);state.notes.set(path,label);state.updatedAt=new Date().toISOString();notify();persistSoon()}
export function clearStagedFile(path){state.files.delete(path);state.notes.delete(path);state.updatedAt=new Date().toISOString();notify();persistSoon()}
export function getStagedFile(path){return state.files.get(path)||null}
export function getStagedSettings(){return state.settings?structuredClone(state.settings):null}
export function getStagedSeo(){return state.seo?structuredClone(state.seo):null}
export function getStagedFiles(){return[...state.files].map(([path,blob])=>({path,blob,label:state.notes.get(path)||path}))}
export function clearDraft(){state.settings=null;state.seo=null;state.files.clear();state.notes.clear();state.restored=false;state.updatedAt=null;notify();clearTimeout(persistTimer);deletePersisted()}
export function getDraftSummary(){const items=[];if(state.settings)items.push({key:'settings',label:state.notes.get('settings')||'Site settings'});if(state.seo)items.push({key:'seo',label:state.notes.get('seo')||'SEO metadata'});for(const path of state.files.keys())items.push({key:path,label:state.notes.get(path)||path});return{enabled:state.enabled,count:items.length,items,hasChanges:items.length>0,restored:state.restored,updatedAt:state.updatedAt}}
export async function publishImmediate({settings=null,seo=null,files=[],saveToLibrary=true,message='Publish managed site change'}={}){if(!isPublisherReady())throw new Error('Unlock the publisher first.');const payloadFiles=await normalizeFiles(files);if(!settings&&!seo&&!payloadFiles.length)throw new Error('There are no changes to publish.');const result=await publisherRequest('/cms/publish',{method:'POST',timeout:90000,headers:{'Content-Type':'application/json'},body:JSON.stringify({settings,seo,files:payloadFiles,saveToLibrary,message})});window.dispatchEvent(new CustomEvent('immortal:cms-published',{detail:result}));return result}
export async function publishDraft({saveToLibrary=true}={}){if(!isPublisherReady())throw new Error('Unlock the publisher first.');const summary=getDraftSummary();if(!summary.hasChanges)throw new Error('There are no staged changes.');const files=[];for(const[path,blob]of state.files)files.push({path,base64:await blob64(blob)});const result=await publisherRequest('/cms/publish',{method:'POST',timeout:90000,headers:{'Content-Type':'application/json'},body:JSON.stringify({settings:state.settings,seo:state.seo,files,saveToLibrary,message:'Publish Immortal site manager draft'})});clearDraft();window.dispatchEvent(new CustomEvent('immortal:cms-published',{detail:result}));return result}
export async function undoLastPublish(){if(!isPublisherReady())throw new Error('Unlock the publisher first.');const result=await publisherRequest('/cms/undo',{method:'POST',timeout:90000,headers:{'Content-Type':'application/json'},body:'{}'});clearDraft();window.dispatchEvent(new CustomEvent('immortal:cms-undo',{detail:result}));return result}
