import{showToast}from'./ux.js';
const KEY='immortalAdminPreferences';
const defaults={density:'comfortable',surface:'soft',accent:'#d7d7d7'};
const $=id=>document.getElementById(id);
function read(){try{return{...defaults,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return{...defaults}}}
function save(value){try{localStorage.setItem(KEY,JSON.stringify(value))}catch{}}
function validColor(v){return/^#[0-9a-f]{6}$/i.test(String(v||''))?String(v).toLowerCase():defaults.accent}
function apply(p){const root=document.documentElement;root.dataset.adminDensity=p.density==='compact'?'compact':'comfortable';root.dataset.adminSurface=p.surface==='black'?'black':'soft';root.style.setProperty('--admin-user-accent',validColor(p.accent));root.style.setProperty('--focus-ring',validColor(p.accent))}
function ensureCard(){const layout=document.querySelector('.system-layout');if(!layout||$('adminPreferencesCard'))return;const card=document.createElement('section');card.className='card settings-card admin-preferences-card';card.id='adminPreferencesCard';card.innerHTML='<div class="card-heading"><div><small>Local preferences</small><h2>Admin appearance</h2></div><i class="bx bx-slider-alt"></i></div><div class="settings-grid"><label><span>Density</span><select id="adminDensity"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></label><label><span>Surface</span><select id="adminSurface"><option value="soft">Soft dark</option><option value="black">True black</option></select></label><label><span>Accent / focus</span><input id="adminAccent" type="color"></label></div><div class="preference-actions"><button class="button secondary" id="resetAdminPreferences" type="button"><i class="bx bx-reset"></i> Reset appearance</button></div><p class="card-copy">These settings only affect this browser. They are never published to your website.</p>';layout.append(card)}
function sync(p){$('adminDensity').value=p.density;$('adminSurface').value=p.surface;$('adminAccent').value=validColor(p.accent)}
export function initAdminPreferences(){const initial=read();apply(initial);ensureCard();sync(initial);const update=()=>{const p={density:$('adminDensity').value,surface:$('adminSurface').value,accent:$('adminAccent').value};save(p);apply(p)};['adminDensity','adminSurface','adminAccent'].forEach(id=>$(id)?.addEventListener('input',update));['adminDensity','adminSurface'].forEach(id=>$(id)?.addEventListener('change',update));$('resetAdminPreferences')?.addEventListener('click',()=>{save(defaults);apply(defaults);sync(defaults);showToast('Admin appearance reset.',{type:'success',duration:2400})})}
