import {decodeImageFile,coverScale,drawCrop,canvasBlob,formatBytes,sha256} from './image-tools.js';
import {publisherRequest,isPublisherReady,onAuthChange} from './auth.js';
import {applyRealPreview,loadActivity} from './site-controls.js';
const $=id=>document.getElementById(id);
const SIZE=720,MAX_SOURCE=30*1024*1024;
const ctx=$('cropCanvas').getContext('2d',{willReadFrequently:true});
const themeEngine=window.ProfilePictureTheme?new window.ProfilePictureTheme('[data-profile-theme-source-never]'):null;
const state={source:null,file:null,palette:null,currentPalette:null,baseScale:1,zoom:1,offsetX:0,offsetY:0,pointers:new Map(),pinchStartDistance:0,pinchStartZoom:1,drag:null};
function short(v,max=80){const s=String(v||'');return s.length>max?`${s.slice(0,max-1)}…`:s}
function formatDate(value){try{return new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))}catch{return value||'Unknown time'}}
function setStatus(message,type=''){const el=$('publishStatus');el.textContent=message;el.className=`publish-status${type?` ${type}`:''}`}
function setDeploy(mode,title,detail){$('deployState').dataset.state=mode;$('deployState').querySelector('strong').textContent=title;$('deployDetail').textContent=detail}
function paletteFrom(element){if(!themeEngine)return null;try{const dominant=themeEngine.getDominantColor(element);return dominant?themeEngine.buildPalette(dominant):null}catch{return null}}
function paletteHex(p){return p&&themeEngine?{main:themeEngine.toHex(p.main),secondary:themeEngine.toHex(p.secondary),accent:themeEngine.toHex(p.accent)}:null}
function renderPalette(container,palette){const colors=paletteHex(palette);container.innerHTML=colors?[['Main',colors.main],['Secondary',colors.secondary],['Accent',colors.accent]].map(([label,hex])=>`<span class="swatch" title="${label}: ${hex}"><span class="swatch-dot" style="background:${hex}"></span><span>${hex}</span></span>`).join(''):'<span class="swatch"><span>No colors yet</span></span>'}
function updatePublishState(){$('publishButton').disabled=!(isPublisherReady()&&state.source&&state.palette)}
function loadCurrent(){const url=`../../assets/pfp.jpg?v=${Date.now()}`;$('currentImage').src=url;$('beforeImage').src=url}
function renderCrop(update=false){if(!state.source)return;drawCrop(ctx,state.source.image,state.source.width,state.source.height,state,SIZE,SIZE);if(update)updatePreview()}
function resetCrop(){if(!state.source)return;state.baseScale=coverScale(state.source.width,state.source.height,SIZE,SIZE);state.zoom=1;state.offsetX=0;state.offsetY=0;$('zoomRange').value='1';renderCrop(true)}
async function updatePreview(){state.palette=paletteFrom($('cropCanvas'));renderPalette($('newPalette'),state.palette);const data=$('cropCanvas').toDataURL('image/jpeg',.86);$('afterImage').src=data;$('previewStatus').textContent=state.palette?'Draft applied to actual homepage':'Could not read colors';try{const blob=await canvasBlob($('cropCanvas'),.9);$('sourceInfo').hidden=false;$('sourceInfo').textContent=`${state.file?.name||'Image'} · ${state.source.width}×${state.source.height} · ${formatBytes(state.file?.size||0)} → 720×720 · ${formatBytes(blob.size)}`}catch{}applyRealPreview({image:data,colors:paletteHex(state.palette)});updatePublishState()}
async function selectFile(file){if(!file)return;if(file.size>MAX_SOURCE)return setStatus('That source image is over 30 MB.','error');try{state.source?.close?.();state.source=await decodeImageFile(file);state.file=file;$('emptyEditor').hidden=true;$('cropEditor').hidden=false;resetCrop();setStatus(isPublisherReady()?'Preview ready. Publish when it looks right.':'Preview ready. Unlock the publisher before publishing.')}catch(error){setStatus(error.message||'Could not read that image.','error')}}
function distance(){const pts=[...state.pointers.values()];return pts.length<2?0:Math.hypot(pts[0].x-pts[1].x,pts[0].y-pts[1].y)}
function bindGestures(){const stage=$('cropStage');stage.addEventListener('pointerdown',event=>{state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});stage.setPointerCapture?.(event.pointerId);if(state.pointers.size===1)state.drag={id:event.pointerId,x:event.clientX,y:event.clientY,ox:state.offsetX,oy:state.offsetY};else if(state.pointers.size===2){state.drag=null;state.pinchStartDistance=distance();state.pinchStartZoom=state.zoom}});stage.addEventListener('pointermove',event=>{if(!state.pointers.has(event.pointerId))return;state.pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(state.pointers.size>=2){const d=distance();if(state.pinchStartDistance)state.zoom=Math.max(1,Math.min(3,state.pinchStartZoom*d/state.pinchStartDistance));$('zoomRange').value=String(state.zoom);renderCrop(false);return}if(!state.drag||state.drag.id!==event.pointerId)return;const rect=$('cropCanvas').getBoundingClientRect(),scale=SIZE/rect.width;state.offsetX=state.drag.ox+(event.clientX-state.drag.x)*scale;state.offsetY=state.drag.oy+(event.clientY-state.drag.y)*scale;renderCrop(false)});const finish=event=>{state.pointers.delete(event.pointerId);stage.releasePointerCapture?.(event.pointerId);state.drag=null;if(!state.pointers.size)renderCrop(true)};stage.addEventListener('pointerup',finish);stage.addEventListener('pointercancel',finish)}
async function waitForLive(expected,timeout=120000){setDeploy('working','Waiting for GitHub Pages','Checking the live image for the exact new file…');const start=Date.now();while(Date.now()-start<timeout){try{const response=await fetch(`../../assets/pfp.jpg?live=${Date.now()}`,{cache:'no-store'});if(response.ok&&await sha256(await response.blob())===expected){setDeploy('live','Live on the website','GitHub Pages is serving the new profile picture.');loadCurrent();return true}}catch{}await new Promise(r=>setTimeout(r,5000))}setDeploy('error','Commit published, Pages still pending','The commit succeeded, but the live cache has not caught up yet.');return false}
async function publish(){if($('publishButton').disabled)return;const button=$('publishButton');button.disabled=true;button.innerHTML='<i class="bx bx-loader-alt bx-spin"></i> Updating…';$('commitLink').hidden=true;try{const blob=await canvasBlob($('cropCanvas'),.9),expected=await sha256(blob),result=await publisherRequest('/profile',{method:'POST',timeout:30000,headers:{'Content-Type':'image/jpeg'},body:blob});$('currentImage').src=$('cropCanvas').toDataURL('image/jpeg',.9);$('beforeImage').src=$('currentImage').src;setStatus('GitHub commit created. Waiting for the live site…','success');if(result.commitUrl){$('commitLink').href=result.commitUrl;$('commitLink').hidden=false}Promise.allSettled([loadHistory(),loadActivity()]);waitForLive(expected)}catch(error){setDeploy('error','Publish failed','The live site was not changed.');setStatus(error.message||'Could not publish.','error')}finally{button.innerHTML='<i class="bx bx-upload"></i> Update profile picture';updatePublishState()}}
export async function loadHistory(){if(!isPublisherReady())return;const box=$('historyList');box.innerHTML='<div class="history-empty">Loading history…</div>';try{const{history=[]}=await publisherRequest('/profile/history?limit=10');box.replaceChildren();if(!history.length){box.innerHTML='<div class="history-empty">No profile history yet.</div>';return}history.forEach((item,index)=>{const row=document.createElement('div');row.className='history-item';row.innerHTML=`<img src="${item.thumbnailUrl}?v=${item.shortSha}" alt="Previous profile picture"><div class="history-copy"><strong>${index===0?'Current · ':''}${short(item.message,48)}</strong><small>${formatDate(item.date)} · ${item.shortSha}</small></div><div class="history-actions"><button type="button" ${index===0?'disabled':''}>Restore</button>${item.commitUrl?`<a href="${item.commitUrl}" target="_blank" rel="noopener">Commit</a>`:''}</div>`;const button=row.querySelector('button');if(index!==0)button.addEventListener('click',async()=>{if(!confirm('Restore this profile picture?'))return;button.disabled=true;button.textContent='Restoring…';try{await publisherRequest('/profile/restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sha:item.sha}),timeout:30000});setStatus('Previous profile picture restored.','success');loadCurrent();await Promise.allSettled([loadHistory(),loadActivity()])}catch(error){setStatus(error.message||'Restore failed.','error')}finally{button.disabled=false;button.textContent='Restore'}});box.append(row)})}catch(error){box.innerHTML=`<div class="history-empty">${short(error.message)}</div>`}}
export function initProfileEditor(){$('currentImage').addEventListener('load',()=>{state.currentPalette=paletteFrom($('currentImage'));renderPalette($('currentPalette'),state.currentPalette);if(!state.palette)applyRealPreview({colors:paletteHex(state.currentPalette)})});renderPalette($('newPalette'),null);loadCurrent();$('refreshCurrent').addEventListener('click',loadCurrent);$('imageInput').addEventListener('change',()=>selectFile($('imageInput').files?.[0]));$('resetCrop').addEventListener('click',resetCrop);$('centerCrop').addEventListener('click',()=>{state.offsetX=0;state.offsetY=0;renderCrop(true)});$('zoomRange').addEventListener('input',()=>{state.zoom=Number($('zoomRange').value)||1;renderCrop(false)});$('zoomRange').addEventListener('change',()=>renderCrop(true));bindGestures();$('uploadDropZone').addEventListener('dragover',event=>{event.preventDefault();$('uploadDropZone').classList.add('dragging')});$('uploadDropZone').addEventListener('dragleave',()=>$('uploadDropZone').classList.remove('dragging'));$('uploadDropZone').addEventListener('drop',event=>{event.preventDefault();$('uploadDropZone').classList.remove('dragging');selectFile([...event.dataTransfer.files].find(file=>file.type.startsWith('image/')||/\.(heic|heif)$/i.test(file.name)))});window.addEventListener('paste',event=>{if(/INPUT|TEXTAREA/.test(document.activeElement?.tagName||''))return;const file=[...(event.clipboardData?.files||[])].find(item=>item.type.startsWith('image/'));if(file)selectFile(file)});$('publishButton').addEventListener('click',publish);$('refreshHistory').addEventListener('click',loadHistory);onAuthChange(ready=>{updatePublishState();if(ready)loadHistory()});window.addEventListener('immortal:snapshot-restored',()=>{loadCurrent();loadHistory()});window.addEventListener('beforeunload',()=>state.source?.close?.())}
