import{showToast}from'./ux.js';
const SEEN_KEY='immortalAdminSeenRelease';
const $=id=>document.getElementById(id);
let release=null;
function seen(){try{return localStorage.getItem(SEEN_KEY)||''}catch{return''}}
function markSeen(){if(!release)return;try{localStorage.setItem(SEEN_KEY,release.version)}catch{}}
function ensureModal(){let modal=$('releaseModal');if(modal)return modal;modal=document.createElement('div');modal.id='releaseModal';modal.className='release-modal';modal.hidden=true;modal.innerHTML='<div class="release-backdrop" data-release-close></div><section class="release-card" role="dialog" aria-modal="true" aria-labelledby="releaseTitle"><div class="card-heading"><div><small>Immortal Admin</small><h2 id="releaseTitle">What’s new</h2></div><button class="asset-modal-close" data-release-close type="button" aria-label="Close changelog"><i class="bx bx-x"></i></button></div><div id="releaseBody"></div></section>';document.body.append(modal);modal.querySelectorAll('[data-release-close]').forEach(el=>el.addEventListener('click',()=>{modal.hidden=true;markSeen()}));window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden){modal.hidden=true;markSeen()}});return modal}
function openRelease(){if(!release)return;const modal=ensureModal(),body=$('releaseBody');body.innerHTML=`<div class="release-version">v${release.version} · ${release.name}</div><ul>${(release.highlights||[]).map(v=>`<li>${String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}</li>`).join('')}</ul><small>Released ${new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(release.releasedAt))}</small>`;modal.hidden=false;markSeen()}
function installEntry(){const footer=document.querySelector('.sidebar-footer');if(!footer||$('releaseButton'))return;const button=document.createElement('button');button.id='releaseButton';button.type='button';button.innerHTML='<i class="bx bx-git-branch"></i><span>What’s new</span><small id="adminVersion"></small>';button.addEventListener('click',openRelease);footer.prepend(button);$('adminVersion').textContent=`v${release.version}`}
export async function initReleaseUi(){try{const response=await fetch(`release.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)return;release=await response.json();installEntry();if(release.version&&seen()!==release.version)setTimeout(()=>showToast(`${release.name} is installed.`,{title:`Immortal Admin v${release.version}`,type:'info',duration:9000,actionLabel:'What’s new',onAction:openRelease}),700)}catch{}}
