const DB_NAME='immortal-admin',DB_VERSION=1,STORE='state',KEY='draft-v1';
const $=id=>document.getElementById(id);let urls=[],rendering=false;
function openDb(){return new Promise(resolve=>{try{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>resolve(null)}catch{resolve(null)}})}
async function readDraft(){const db=await openDb();if(!db)return null;return new Promise(resolve=>{try{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(KEY);req.onsuccess=()=>resolve(req.result||null);req.onerror=()=>resolve(null)}catch{resolve(null)}})}
async function liveSettings(){try{const r=await fetch(`../../data/site-settings.json?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():{}}catch{return{}}}
function urlFor(blob){if(!(blob instanceof Blob))return'';const url=URL.createObjectURL(blob);urls.push(url);return url}
function fileMap(draft){return new Map((Array.isArray(draft?.files)?draft.files:[]).filter(v=>v?.path&&v?.blob instanceof Blob).map(v=>[v.path,v.blob]))}
function maintenance(doc,s){let layer=doc.getElementById('stageMaintenance');if(!s.maintenanceEnabled){layer?.remove();return}if(!layer){layer=doc.createElement('div');layer.id='stageMaintenance';doc.body.append(layer)}Object.assign(layer.style,{position:'fixed',inset:'0',zIndex:'999999',display:'grid',placeItems:'center',padding:'28px',background:'rgba(5,5,5,.97)',color:'#f1f1f1',textAlign:'center',fontFamily:'inherit'});layer.replaceChildren();const box=doc.createElement('div'),eyebrow=doc.createElement('small'),h=doc.createElement('h1'),p=doc.createElement('p');box.style.maxWidth='560px';eyebrow.textContent='Immortal';Object.assign(eyebrow.style,{opacity:'.55',letterSpacing:'.16em',textTransform:'uppercase'});h.textContent=s.maintenanceTitle||'Back soon';Object.assign(h.style,{fontSize:'clamp(2rem,7vw,4.4rem)',margin:'.5rem 0 1rem'});p.textContent=s.maintenanceMessage||'';Object.assign(p.style,{opacity:'.68',lineHeight:'1.7'});box.append(eyebrow,h,p);layer.append(box)}
async function waitForFrame(frame){const doc=frame.contentDocument;if(doc&&doc.readyState==='complete')return doc;await new Promise(resolve=>frame.addEventListener('load',resolve,{once:true}));return frame.contentDocument}
async function render(){if(rendering)return;rendering=true;try{urls.forEach(URL.revokeObjectURL);urls=[];const draft=await readDraft(),count=(draft?.settings?1:0)+(draft?.seo?1:0)+(Array.isArray(draft?.files)?draft.files.length:0);if(!draft||!count){$('stageEmpty').style.display='grid';$('stageStatus').textContent='No saved draft';return}$('stageEmpty').style.display='none';const frame=$('stageFrame'),doc=await waitForFrame(frame);if(!doc)return;const s={...await liveSettings(),...(draft.settings||{})},files=fileMap(draft);$('stageStatus').textContent=`${count} staged change${count===1?'':'s'} · browser-local`;
const pfp=urlFor(files.get('assets/pfp.jpg'));if(pfp)doc.querySelectorAll('.profile-img').forEach(img=>img.src=pfp);if(s.themeMode==='manual'){doc.documentElement.style.setProperty('--main-color',s.mainColor||'#fff','important');doc.documentElement.style.setProperty('--secondary-color',s.secondaryColor||'#999','important');doc.documentElement.style.setProperty('--accent-color',s.accentColor||'#ddd','important')}
const bio=doc.querySelector('.tagline.enhanced-tagline');if(bio&&s.bio)bio.textContent=s.bio;const status=doc.querySelector('.status-card .label');if(status&&s.statusText)status.textContent=s.statusText;const commission=doc.querySelector('.commission-cta .btn-text');if(commission)commission.textContent=s.commissionOpen?'Commission':'Commissions Closed';const home=doc.querySelector('.home');if(home){const bg=urlFor(files.get('assets/site-background.jpg'))||'/assets/site-background.jpg';if(s.backgroundEnabled){home.style.backgroundImage=`linear-gradient(rgba(5,5,5,.62),rgba(5,5,5,.82)),url("${bg}")`;home.style.backgroundSize='cover';home.style.backgroundPosition='center'}else home.style.removeProperty('background-image');let banner=home.querySelector(':scope > .stage-preview-banner');if(s.bannerEnabled){if(!banner){banner=doc.createElement('div');banner.className='stage-preview-banner';home.prepend(banner)}Object.assign(banner.style,{position:'absolute',inset:'0',pointerEvents:'none',zIndex:'0',opacity:'.16',backgroundImage:`url("${urlFor(files.get('assets/site-banner.jpg'))||'/assets/site-banner.jpg'}")`,backgroundSize:'cover',backgroundPosition:'center',maskImage:'linear-gradient(to bottom,black,transparent 72%)'})}else banner?.remove()}const fav=urlFor(files.get('assets/site-favicon.jpg'));if(fav&&s.faviconEnabled){let link=doc.querySelector('link[rel="icon"]');if(!link){link=doc.createElement('link');link.rel='icon';doc.head.append(link)}link.href=fav}if(draft.seo?.title)doc.title=draft.seo.title;maintenance(doc,s)}finally{rendering=false}}
$('stageFrame').addEventListener('load',render);$('refreshStage').addEventListener('click',render);window.addEventListener('beforeunload',()=>urls.forEach(URL.revokeObjectURL));render();
