import{getDraftSummary}from'./draft.js';
const $=id=>document.getElementById(id);let confirmResolver=null,lastDialogFocus=null,offlineToast=null,networkInitialized=false,lastOnline=navigator.onLine;
export function friendlyError(error,fallback='Something went wrong.'){const raw=String(error?.message||error||'').trim();if(error?.name==='AbortError'||/aborted|timeout/i.test(raw))return'The request took too long. Check your connection and try again.';if(/failed to fetch|networkerror|network request/i.test(raw))return'Could not reach the publisher. Check your connection and try again.';if(/invalid publisher|publisher is locked|401|unauthorized/i.test(raw))return'Your admin session is locked or expired. Sign in again in System.';if(/cors/i.test(raw))return'The publisher blocked this browser request. Refresh the admin and try again.';return raw||fallback}
export function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureToastContainer(){let c=$('toastRegion');if(c)return c;c=document.createElement('div');c.id='toastRegion';c.className='toast-region';c.setAttribute('aria-live','polite');c.setAttribute('aria-atomic','false');document.body.append(c);return c}
export function showToast(message,{title='',type='info',duration=5200,actionLabel='',onAction=null,persistent=false}={}){const container=ensureToastContainer(),toast=document.createElement('div');toast.className=`admin-toast ${type}`;toast.setAttribute('role',type==='error'?'alert':'status');toast.innerHTML=`<i class="bx ${type==='success'?'bx-check-circle':type==='error'?'bx-error-circle':type==='warning'?'bx-error':'bx-info-circle'}"></i><div class="admin-toast-copy">${title?`<strong>${escapeHtml(title)}</strong>`:''}<span>${escapeHtml(message)}</span></div>${actionLabel?`<button class="toast-action" type="button">${escapeHtml(actionLabel)}</button>`:''}<button class="toast-close" type="button" aria-label="Dismiss notification"><i class="bx bx-x"></i></button>`;container.append(toast);requestAnimationFrame(()=>toast.classList.add('show'));let timer=null;const close=()=>{if(!toast.isConnected)return;clearTimeout(timer);toast.classList.remove('show');setTimeout(()=>toast.remove(),180)};toast.querySelector('.toast-close').addEventListener('click',close);const action=toast.querySelector('.toast-action');if(action)action.addEventListener('click',async()=>{try{await onAction?.()}finally{close()}});if(!persistent&&duration>0)timer=setTimeout(close,duration);return{element:toast,close}}
export function loadingSkeleton(rows=3){return`<div class="skeleton-list" aria-label="Loading" role="status">${Array.from({length:rows},(_,i)=>`<span class="skeleton-row" style="--i:${i}"></span>`).join('')}</div>`}
function ensureConfirm(){let modal=$('adminConfirm');if(modal)return modal;modal=document.createElement('div');modal.id='adminConfirm';modal.className='confirm-modal';modal.hidden=true;modal.innerHTML='<div class="confirm-backdrop" data-confirm-cancel></div><section class="confirm-card" role="alertdialog" aria-modal="true" aria-labelledby="confirmTitle" aria-describedby="confirmMessage"><span class="confirm-icon"><i class="bx bx-shield-quarter"></i></span><div><h2 id="confirmTitle">Confirm action</h2><p id="confirmMessage"></p></div><div class="confirm-actions"><button class="button secondary" type="button" data-confirm-cancel>Cancel</button><button class="button primary" id="confirmAccept" type="button">Continue</button></div></section>';document.body.append(modal);modal.querySelectorAll('[data-confirm-cancel]').forEach(el=>el.addEventListener('click',()=>finishConfirm(false)));$('confirmAccept').addEventListener('click',()=>finishConfirm(true));return modal}
function finishConfirm(value){const modal=$('adminConfirm');if(!modal||modal.hidden)return;modal.hidden=true;document.body.classList.remove('modal-open');const resolve=confirmResolver;confirmResolver=null;resolve?.(value);lastDialogFocus?.focus?.();lastDialogFocus=null}
export function confirmAction({title='Confirm action',message='',confirmLabel='Continue',danger=false}={}){const modal=ensureConfirm();if(confirmResolver)finishConfirm(false);lastDialogFocus=document.activeElement;modal.querySelector('#confirmTitle').textContent=title;modal.querySelector('#confirmMessage').textContent=message;const accept=$('confirmAccept');accept.textContent=confirmLabel;accept.classList.toggle('danger',danger);modal.hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>accept.focus());return new Promise(resolve=>{confirmResolver=resolve})}
function openDialog(){return[...document.querySelectorAll('[role="dialog"],[role="alertdialog"]')].find(el=>!el.closest('[hidden]')&&!el.hidden)}
function dialogFocusables(dialog){return[...dialog.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),summary,[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null)}
function onKeydown(event){const dialog=openDialog();if(event.key==='Escape'&&confirmResolver){event.preventDefault();finishConfirm(false);return}if(event.key!=='Tab'||!dialog)return;const items=dialogFocusables(dialog);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function warnBeforeLeave(event){if(!getDraftSummary().hasChanges)return;event.preventDefault();event.returnValue=''}
function showOffline(){if(!offlineToast)offlineToast=showToast('You are offline. Draft edits remain in this tab, but publishing needs a connection.',{title:'Offline',type:'warning',persistent:true})}
function setNetworkState(){const online=navigator.onLine;document.documentElement.dataset.network=online?'online':'offline';if(!networkInitialized){networkInitialized=true;lastOnline=online;if(!online)showOffline();return}if(online&&!lastOnline){offlineToast?.close?.();offlineToast=null;showToast('Connection restored.',{type:'success',duration:2600})}else if(!online&&lastOnline)showOffline();lastOnline=online}
function enhanceBrand(){const link=document.querySelector('a.sidebar-brand'),close=$('sidebarCloseButton');if(!link||!close||close.parentElement!==link)return;const wrapper=document.createElement('div');wrapper.className='sidebar-brand';link.before(wrapper);link.classList.remove('sidebar-brand');link.classList.add('sidebar-brand-link');wrapper.append(link,close)}
function enhanceDocument(){const main=document.querySelector('.admin-main');if(main&&!main.id)main.id='adminMain';if(!document.querySelector('.skip-link')){const skip=document.createElement('a');skip.className='skip-link';skip.href='#adminMain';skip.textContent='Skip to admin content';document.body.prepend(skip)}enhanceBrand();$('mobileMenuButton')?.setAttribute('aria-expanded','false');const icon='admin-icon.svg';document.querySelector('link[rel="icon"]')?.setAttribute('href',icon);document.querySelector('link[rel="apple-touch-icon"]')?.setAttribute('href',icon);if(!document.querySelector('.offline-badge')){const badge=document.createElement('span');badge.className='offline-badge status-chip';badge.innerHTML='<i class="bx bx-wifi-off"></i> Offline';document.querySelector('.admin-topbar-actions')?.prepend(badge)}
  if(!document.querySelector('.mobile-bottom-nav')){const nav=document.createElement('nav');nav.className='mobile-bottom-nav';nav.setAttribute('aria-label','Quick admin navigation');nav.innerHTML='<button data-workspace-target="overview" type="button"><i class="bx bx-grid-alt"></i><span>Home</span></button><button data-workspace-target="profile" type="button"><i class="bx bx-user-circle"></i><span>Profile</span></button><button data-workspace-target="appearance" type="button"><i class="bx bx-palette"></i><span>Look</span></button><button data-workspace-target="publish" type="button"><i class="bx bx-cloud-upload"></i><span>Publish</span></button><button id="mobileMoreButton" type="button"><i class="bx bx-menu"></i><span>More</span></button>';document.body.append(nav)}
  const publishCard=document.querySelector('.publish-workspace-card');if(publishCard&&!$('deployTimeline')){const section=document.createElement('div');section.className='deployment-progress';section.innerHTML='<div class="form-section-title"><div><strong>Deployment</strong><small>Live progress after Publish All.</small></div></div><ol class="deploy-timeline" id="deployTimeline" aria-label="Deployment progress"><li data-step="saved"><span class="step-dot"><i class="bx bx-save"></i></span><span>Saved</span></li><li data-step="commit"><span class="step-dot"><i class="bx bxl-github"></i></span><span>GitHub commit</span></li><li data-step="pages"><span class="step-dot"><i class="bx bx-loader-circle"></i></span><span>Pages building</span></li><li data-step="live"><span class="step-dot"><i class="bx bx-globe"></i></span><span>Live</span></li></ol><div class="deploy-timeline-detail" id="deployTimelineDetail">No deployment running.</div>';publishCard.append(section)}
  const logs=$('cmsLogs');if(logs&&!$('logFilter')){const toolbar=document.createElement('div');toolbar.className='log-toolbar';toolbar.innerHTML='<label>Filter <select id="logFilter"><option value="all">All activity</option><option value="error">Errors</option><option value="publish">Publishing</option><option value="system">System</option></select></label><span class="status-chip"><i class="bx bx-copy"></i> Copy details</span>';logs.before(toolbar)}
  const setup=$('publisherSetup');if(setup&&!$('emergencyAuth')){const fields=setup.querySelector('.publisher-fields'),remember=setup.querySelector('.remember-row'),unlock=$('savePublisherButton'),help=[...setup.querySelectorAll('.publisher-help')].at(-1),divider=setup.querySelector('.auth-divider');if(fields&&unlock){divider?.remove();const details=document.createElement('details');details.id='emergencyAuth';details.className='emergency-auth';details.innerHTML='<summary><i class="bx bx-key"></i> Emergency publisher key</summary><div class="emergency-auth-body"></div>';const body=details.querySelector('.emergency-auth-body');body.append(fields);if(remember)body.append(remember);body.append(unlock);if(help)body.append(help);setup.append(details);const note=document.createElement('p');note.className='auth-primary-note';note.textContent='GitHub sign-in is the preferred everyday login. Keep the private key only as an emergency fallback.';setup.insertBefore(note,details)}}}
export function initUx(){enhanceDocument();ensureToastContainer();ensureConfirm();window.addEventListener('beforeunload',warnBeforeLeave);window.addEventListener('keydown',onKeydown);window.addEventListener('offline',setNetworkState);window.addEventListener('online',setNetworkState);window.addEventListener('immortal:toast',event=>showToast(event.detail?.message||'',{type:event.detail?.type||'info'}));$('mobileMoreButton')?.addEventListener('click',()=>{document.body.classList.add('admin-menu-open');$('mobileMenuButton')?.setAttribute('aria-expanded','true')});setNetworkState();window.addEventListener('unhandledrejection',event=>{const message=friendlyError(event.reason,'Unexpected background error.');showToast(message,{type:'error'});window.dispatchEvent(new CustomEvent('immortal:client-error',{detail:{message}}))});window.addEventListener('error',event=>{if(!event.message)return;showToast(event.message,{type:'error'});window.dispatchEvent(new CustomEvent('immortal:client-error',{detail:{message:event.message}}))})}
