import{getDraftSummary}from'./draft.js';
const $=id=>document.getElementById(id);let confirmResolver=null,lastDialogFocus=null,offlineToast=null;
export function friendlyError(error,fallback='Something went wrong.'){const raw=String(error?.message||error||'').trim();if(error?.name==='AbortError'||/aborted|timeout/i.test(raw))return'The request took too long. Check your connection and try again.';if(/failed to fetch|networkerror|network request/i.test(raw))return'Could not reach the publisher. Check your connection and try again.';if(/invalid publisher|publisher is locked|401|unauthorized/i.test(raw))return'Your admin session is locked or expired. Sign in again in System.';if(/cors/i.test(raw))return'The publisher blocked this browser request. Refresh the admin and try again.';return raw||fallback}
function ensureToastContainer(){let c=$('toastRegion');if(c)return c;c=document.createElement('div');c.id='toastRegion';c.className='toast-region';c.setAttribute('aria-live','polite');c.setAttribute('aria-atomic','false');document.body.append(c);return c}
export function showToast(message,{title='',type='info',duration=5200,actionLabel='',onAction=null,persistent=false}={}){const container=ensureToastContainer(),toast=document.createElement('div');toast.className=`admin-toast ${type}`;toast.setAttribute('role',type==='error'?'alert':'status');toast.innerHTML=`<i class="bx ${type==='success'?'bx-check-circle':type==='error'?'bx-error-circle':type==='warning'?'bx-error':'bx-info-circle'}"></i><div class="admin-toast-copy">${title?`<strong>${escapeHtml(title)}</strong>`:''}<span>${escapeHtml(message)}</span></div>${actionLabel?`<button class="toast-action" type="button">${escapeHtml(actionLabel)}</button>`:''}<button class="toast-close" type="button" aria-label="Dismiss notification"><i class="bx bx-x"></i></button>`;container.append(toast);requestAnimationFrame(()=>toast.classList.add('show'));let timer=null;const close=()=>{if(!toast.isConnected)return;clearTimeout(timer);toast.classList.remove('show');setTimeout(()=>toast.remove(),180)};toast.querySelector('.toast-close').addEventListener('click',close);const action=toast.querySelector('.toast-action');if(action)action.addEventListener('click',async()=>{try{await onAction?.()}finally{close()}});if(!persistent&&duration>0)timer=setTimeout(close,duration);return{element:toast,close}}
export function loadingSkeleton(rows=3){return`<div class="skeleton-list" aria-label="Loading" role="status">${Array.from({length:rows},(_,i)=>`<span class="skeleton-row" style="--i:${i}"></span>`).join('')}</div>`}
export function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function ensureConfirm(){let modal=$('adminConfirm');if(modal)return modal;modal=document.createElement('div');modal.id='adminConfirm';modal.className='confirm-modal';modal.hidden=true;modal.innerHTML='<div class="confirm-backdrop" data-confirm-cancel></div><section class="confirm-card" role="alertdialog" aria-modal="true" aria-labelledby="confirmTitle" aria-describedby="confirmMessage"><span class="confirm-icon"><i class="bx bx-shield-quarter"></i></span><div><h2 id="confirmTitle">Confirm action</h2><p id="confirmMessage"></p></div><div class="confirm-actions"><button class="button secondary" type="button" data-confirm-cancel>Cancel</button><button class="button primary" id="confirmAccept" type="button">Continue</button></div></section>';document.body.append(modal);modal.querySelectorAll('[data-confirm-cancel]').forEach(el=>el.addEventListener('click',()=>finishConfirm(false)));$('confirmAccept').addEventListener('click',()=>finishConfirm(true));return modal}
function finishConfirm(value){const modal=$('adminConfirm');if(!modal||modal.hidden)return;modal.hidden=true;document.body.classList.remove('modal-open');const resolve=confirmResolver;confirmResolver=null;resolve?.(value);lastDialogFocus?.focus?.();lastDialogFocus=null}
export function confirmAction({title='Confirm action',message='',confirmLabel='Continue',danger=false}={}){const modal=ensureConfirm();if(confirmResolver)finishConfirm(false);lastDialogFocus=document.activeElement;modal.querySelector('#confirmTitle').textContent=title;modal.querySelector('#confirmMessage').textContent=message;const accept=$('confirmAccept');accept.textContent=confirmLabel;accept.classList.toggle('danger',danger);modal.hidden=false;document.body.classList.add('modal-open');requestAnimationFrame(()=>accept.focus());return new Promise(resolve=>{confirmResolver=resolve})}
function openDialog(){return[...document.querySelectorAll('[role="dialog"],[role="alertdialog"]')].find(el=>!el.closest('[hidden]')&&!el.hidden)}
function dialogFocusables(dialog){return[...dialog.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null)}
function onKeydown(event){const dialog=openDialog();if(event.key==='Escape'&&confirmResolver){event.preventDefault();finishConfirm(false);return}if(event.key!=='Tab'||!dialog)return;const items=dialogFocusables(dialog);if(!items.length)return;const first=items[0],last=items.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}
function warnBeforeLeave(event){if(!getDraftSummary().hasChanges)return;event.preventDefault();event.returnValue=''}
function setNetworkState(){document.documentElement.dataset.network=navigator.onLine?'online':'offline';if(navigator.onLine){offlineToast?.close?.();offlineToast=null;showToast('Connection restored.',{type:'success',duration:2600})}else if(!offlineToast){offlineToast=showToast('You are offline. Draft edits remain in this tab, but publishing needs a connection.',{title:'Offline',type:'warning',persistent:true})}}
export function initUx(){ensureToastContainer();ensureConfirm();window.addEventListener('beforeunload',warnBeforeLeave);window.addEventListener('keydown',onKeydown);window.addEventListener('offline',setNetworkState);window.addEventListener('online',setNetworkState);$('mobileMoreButton')?.addEventListener('click',()=>{document.body.classList.add('admin-menu-open');$('mobileMenuButton')?.setAttribute('aria-expanded','true')});setNetworkState();window.addEventListener('unhandledrejection',event=>{const message=friendlyError(event.reason,'Unexpected background error.');showToast(message,{type:'error'});window.dispatchEvent(new CustomEvent('immortal:client-error',{detail:{message}}))});window.addEventListener('error',event=>{if(!event.message)return;showToast(event.message,{type:'error'});window.dispatchEvent(new CustomEvent('immortal:client-error',{detail:{message:event.message}}))})}
